#!/bin/bash
#
# usage:
#
# panorama2img <size> <user> <map nr> <png outputfile>
#
# ex.: panorama2img 1024x768x24 omdadmin 1 /tmp/test.png
#

# read rc files if exist
[ -e ~/.profile ] && . ~/.profile

SIZE=$1
USER=$2
MAP=$3
OUTPUT=$4

if [ "x$OUTPUT" = "x" ]; then
  echo "Usage: panorama2img <size> <user> <map nr> <png outputfile>"
  echo ""
  echo "ex.: panorama2img 1024x768x24 omdadmin 1 /tmp/test.png"
  exit 3;
fi

WKHTMLTOIMAGE=$OMD_ROOT/bin/wkhtmltoimage
SESSIONID=$(date +%s%N)
SESSIONFILE=$OMD_ROOT/var/thruk/sessions/$SESSIONID

WIDTH=$(echo $SIZE | awk -F x '{ print $1}')
HEIGHT=$(echo $SIZE | awk -F x '{ print $2}')

# create fake session
echo "none~~~127.0.0.1~~~$USER" > $SESSIONFILE

DISP=$RANDOM
let "DISP %= 500"
while [ -f /tmp/.X${DISP}-lock ];do
  DISP=$RANDOM
  let "DISP %= 500";
done;
XAUTHORITY=`mktemp`;
TMPLOG=`mktemp`;
Xvfb -screen 0 $SIZE -dpi 60 -terminate -auth $XAUTHORITY -nolisten tcp :$DISP >$TMPLOG 2>&1 &
xpid=$!

# wait for xauth
for x in seq 10; do
    sleep 1;
    [ -e $XAUTHORITY ] && break;
done

rm -f $OUTPUT
DISPLAY=:$DISP $WKHTMLTOIMAGE \
        --use-xserver \
        --disable-smart-width --width $WIDTH --height $HEIGHT \
        --quality 100 \
        --javascript-delay 10000 \
        --crop-h 5000 --crop-w 5000 --crop-x 0 --crop-y 3 \
        --cookie thruk_auth "$SESSIONID" \
        "https://localhost/$OMD_SITE/thruk/cgi-bin/panorama.cgi#$MAP" "$OUTPUT" 2>&1

# ensure file is not owned by root
if [ -e "$OUTPUT" -a $UID == 0 ]; then
    usr=`ls -la "$INPUT" | awk '{ print $3 }'`
    grp=`ls -la "$INPUT" | awk '{ print $4 }'`
    chown $usr:$grp $OUTPUT
fi

kill $xpid >/dev/null 2>&1
rm -f $TMPLOG $XAUTHORITY $SESSIONFILE
