---
layout: docs
title: REST API Commands
breadcrumb: [ "advanced.html", "Advanced", "Rest" ]
---


== REST API Commands
{% include new_since.ad version="2.24" %}
Thruk offers a rest api to expose various aspects of Thruk itself and
livestatus information.

Read more about the link:rest.html[REST API] itself. This page contains
the comprehensive list of all available external commands.

== Example Usage

All examples can be found on the link:rest_examples.html#sending_commands[REST API Examples page].

== Endpoints

See examples and detailed description for all available rest api command urls:

=== POST /hostgroups/<name>/cmd/...

external commands are documented in detail on a separate commands page.
list of supported commands:

 - link:rest_commands.html#post-hostgroups-name-cmd-disable-hostgroup-host-checks[disable_hostgroup_host_checks]
 - link:rest_commands.html#post-hostgroups-name-cmd-disable-hostgroup-host-notifications[disable_hostgroup_host_notifications]
 - link:rest_commands.html#post-hostgroups-name-cmd-disable-hostgroup-svc-checks[disable_hostgroup_svc_checks]
 - link:rest_commands.html#post-hostgroups-name-cmd-disable-hostgroup-svc-notifications[disable_hostgroup_svc_notifications]
 - link:rest_commands.html#post-hostgroups-name-cmd-enable-hostgroup-host-checks[enable_hostgroup_host_checks]
 - link:rest_commands.html#post-hostgroups-name-cmd-enable-hostgroup-host-notifications[enable_hostgroup_host_notifications]
 - link:rest_commands.html#post-hostgroups-name-cmd-enable-hostgroup-svc-checks[enable_hostgroup_svc_checks]
 - link:rest_commands.html#post-hostgroups-name-cmd-enable-hostgroup-svc-notifications[enable_hostgroup_svc_notifications]
 - link:rest_commands.html#post-hostgroups-name-cmd-schedule-hostgroup-host-downtime[schedule_hostgroup_host_downtime]
 - link:rest_commands.html#post-hostgroups-name-cmd-schedule-hostgroup-svc-downtime[schedule_hostgroup_svc_downtime]

=== POST /hostgroups/<name>/cmd/disable_hostgroup_host_checks

Sends the DISABLE_HOSTGROUP_HOST_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_hostgroup_host_checks.html for details.

=== POST /hostgroups/<name>/cmd/disable_hostgroup_host_notifications

Sends the DISABLE_HOSTGROUP_HOST_NOTIFICATIONS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_hostgroup_host_notifications.html for details.

=== POST /hostgroups/<name>/cmd/disable_hostgroup_svc_checks

Sends the DISABLE_HOSTGROUP_SVC_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_hostgroup_svc_checks.html for details.

=== POST /hostgroups/<name>/cmd/disable_hostgroup_svc_notifications

Sends the DISABLE_HOSTGROUP_SVC_NOTIFICATIONS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_hostgroup_svc_notifications.html for details.

=== POST /hostgroups/<name>/cmd/enable_hostgroup_host_checks

Sends the ENABLE_HOSTGROUP_HOST_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_hostgroup_host_checks.html for details.

=== POST /hostgroups/<name>/cmd/enable_hostgroup_host_notifications

Sends the ENABLE_HOSTGROUP_HOST_NOTIFICATIONS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_hostgroup_host_notifications.html for details.

=== POST /hostgroups/<name>/cmd/enable_hostgroup_svc_checks

Sends the ENABLE_HOSTGROUP_SVC_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_hostgroup_svc_checks.html for details.

=== POST /hostgroups/<name>/cmd/enable_hostgroup_svc_notifications

Sends the ENABLE_HOSTGROUP_SVC_NOTIFICATIONS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_hostgroup_svc_notifications.html for details.

=== POST /hostgroups/<name>/cmd/schedule_hostgroup_host_downtime

Sends the SCHEDULE_HOSTGROUP_HOST_DOWNTIME command.

Required arguments:

  * comment_data

Optional arguments:

  * start_time
  * end_time
  * fixed
  * duration
  * comment_author

See http://www.naemon.org/documentation/developer/externalcommands/schedule_hostgroup_host_downtime.html for details.

=== POST /hostgroups/<name>/cmd/schedule_hostgroup_svc_downtime

Sends the SCHEDULE_HOSTGROUP_SVC_DOWNTIME command.

Required arguments:

  * comment_data

Optional arguments:

  * start_time
  * end_time
  * fixed
  * duration
  * comment_author

See http://www.naemon.org/documentation/developer/externalcommands/schedule_hostgroup_svc_downtime.html for details.

=== POST /hosts/<name>/cmd/...

external commands are documented in detail on a separate commands page.
list of supported commands:

 - link:rest_commands.html#post-hosts-name-cmd-acknowledge-host-problem[acknowledge_host_problem]
 - link:rest_commands.html#post-hosts-name-cmd-acknowledge-host-problem-expire[acknowledge_host_problem_expire]
 - link:rest_commands.html#post-hosts-name-cmd-add-host-comment[add_host_comment]
 - link:rest_commands.html#post-hosts-name-cmd-change-host-modattr[change_host_modattr]
 - link:rest_commands.html#post-hosts-name-cmd-del-all-host-comments[del_all_host_comments]
 - link:rest_commands.html#post-hosts-name-cmd-delay-host-notification[delay_host_notification]
 - link:rest_commands.html#post-hosts-name-cmd-disable-all-notifications-beyond-host[disable_all_notifications_beyond_host]
 - link:rest_commands.html#post-hosts-name-cmd-disable-host-and-child-notifications[disable_host_and_child_notifications]
 - link:rest_commands.html#post-hosts-name-cmd-disable-host-check[disable_host_check]
 - link:rest_commands.html#post-hosts-name-cmd-disable-host-event-handler[disable_host_event_handler]
 - link:rest_commands.html#post-hosts-name-cmd-disable-host-flap-detection[disable_host_flap_detection]
 - link:rest_commands.html#post-hosts-name-cmd-disable-host-notifications[disable_host_notifications]
 - link:rest_commands.html#post-hosts-name-cmd-disable-host-svc-checks[disable_host_svc_checks]
 - link:rest_commands.html#post-hosts-name-cmd-disable-host-svc-notifications[disable_host_svc_notifications]
 - link:rest_commands.html#post-hosts-name-cmd-disable-passive-host-checks[disable_passive_host_checks]
 - link:rest_commands.html#post-hosts-name-cmd-enable-all-notifications-beyond-host[enable_all_notifications_beyond_host]
 - link:rest_commands.html#post-hosts-name-cmd-enable-host-and-child-notifications[enable_host_and_child_notifications]
 - link:rest_commands.html#post-hosts-name-cmd-enable-host-check[enable_host_check]
 - link:rest_commands.html#post-hosts-name-cmd-enable-host-event-handler[enable_host_event_handler]
 - link:rest_commands.html#post-hosts-name-cmd-enable-host-flap-detection[enable_host_flap_detection]
 - link:rest_commands.html#post-hosts-name-cmd-enable-host-notifications[enable_host_notifications]
 - link:rest_commands.html#post-hosts-name-cmd-enable-host-svc-checks[enable_host_svc_checks]
 - link:rest_commands.html#post-hosts-name-cmd-enable-host-svc-notifications[enable_host_svc_notifications]
 - link:rest_commands.html#post-hosts-name-cmd-enable-passive-host-checks[enable_passive_host_checks]
 - link:rest_commands.html#post-hosts-name-cmd-process-host-check-result[process_host_check_result]
 - link:rest_commands.html#post-hosts-name-cmd-remove-host-acknowledgement[remove_host_acknowledgement]
 - link:rest_commands.html#post-hosts-name-cmd-schedule-and-propagate-host-downtime[schedule_and_propagate_host_downtime]
 - link:rest_commands.html#post-hosts-name-cmd-schedule-and-propagate-triggered-host-downtime[schedule_and_propagate_triggered_host_downtime]
 - link:rest_commands.html#post-hosts-name-cmd-schedule-forced-host-check[schedule_forced_host_check]
 - link:rest_commands.html#post-hosts-name-cmd-schedule-forced-host-svc-checks[schedule_forced_host_svc_checks]
 - link:rest_commands.html#post-hosts-name-cmd-schedule-host-check[schedule_host_check]
 - link:rest_commands.html#post-hosts-name-cmd-schedule-host-downtime[schedule_host_downtime]
 - link:rest_commands.html#post-hosts-name-cmd-schedule-host-svc-checks[schedule_host_svc_checks]
 - link:rest_commands.html#post-hosts-name-cmd-schedule-host-svc-downtime[schedule_host_svc_downtime]
 - link:rest_commands.html#post-hosts-name-cmd-send-custom-host-notification[send_custom_host_notification]
 - link:rest_commands.html#post-hosts-name-cmd-start-obsessing-over-host[start_obsessing_over_host]
 - link:rest_commands.html#post-hosts-name-cmd-stop-obsessing-over-host[stop_obsessing_over_host]

=== POST /hosts/<name>/cmd/acknowledge_host_problem

Sends the ACKNOWLEDGE_HOST_PROBLEM command.

Required arguments:

  * comment_data

Optional arguments:

  * sticky_ack
  * send_notification
  * persistent_comment
  * comment_author

See http://www.naemon.org/documentation/developer/externalcommands/acknowledge_host_problem.html for details.

=== POST /hosts/<name>/cmd/acknowledge_host_problem_expire

Sends the ACKNOWLEDGE_HOST_PROBLEM_EXPIRE command.

Required arguments:

  * comment_data

Optional arguments:

  * sticky_ack
  * send_notification
  * persistent_comment
  * end_time
  * comment_author

See http://www.naemon.org/documentation/developer/externalcommands/acknowledge_host_problem_expire.html for details.

=== POST /hosts/<name>/cmd/add_host_comment

Sends the ADD_HOST_COMMENT command.

Required arguments:

  * comment_data

Optional arguments:

  * persistent_comment
  * comment_author

See http://www.naemon.org/documentation/developer/externalcommands/add_host_comment.html for details.

=== POST /hosts/<name>/cmd/change_host_modattr

Sends the CHANGE_HOST_MODATTR command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/change_host_modattr.html for details.

=== POST /hosts/<name>/cmd/del_all_host_comments

Sends the DEL_ALL_HOST_COMMENTS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/del_all_host_comments.html for details.

=== POST /hosts/<name>/cmd/delay_host_notification

Sends the DELAY_HOST_NOTIFICATION command.

Required arguments:

  * notification_time

See http://www.naemon.org/documentation/developer/externalcommands/delay_host_notification.html for details.

=== POST /hosts/<name>/cmd/disable_all_notifications_beyond_host

Sends the DISABLE_ALL_NOTIFICATIONS_BEYOND_HOST command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_all_notifications_beyond_host.html for details.

=== POST /hosts/<name>/cmd/disable_host_and_child_notifications

Sends the DISABLE_HOST_AND_CHILD_NOTIFICATIONS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_host_and_child_notifications.html for details.

=== POST /hosts/<name>/cmd/disable_host_check

Sends the DISABLE_HOST_CHECK command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_host_check.html for details.

=== POST /hosts/<name>/cmd/disable_host_event_handler

Sends the DISABLE_HOST_EVENT_HANDLER command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_host_event_handler.html for details.

=== POST /hosts/<name>/cmd/disable_host_flap_detection

Sends the DISABLE_HOST_FLAP_DETECTION command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_host_flap_detection.html for details.

=== POST /hosts/<name>/cmd/disable_host_notifications

Sends the DISABLE_HOST_NOTIFICATIONS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_host_notifications.html for details.

=== POST /hosts/<name>/cmd/disable_host_svc_checks

Sends the DISABLE_HOST_SVC_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_host_svc_checks.html for details.

=== POST /hosts/<name>/cmd/disable_host_svc_notifications

Sends the DISABLE_HOST_SVC_NOTIFICATIONS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_host_svc_notifications.html for details.

=== POST /hosts/<name>/cmd/disable_passive_host_checks

Sends the DISABLE_PASSIVE_HOST_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_passive_host_checks.html for details.

=== POST /hosts/<name>/cmd/enable_all_notifications_beyond_host

Sends the ENABLE_ALL_NOTIFICATIONS_BEYOND_HOST command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_all_notifications_beyond_host.html for details.

=== POST /hosts/<name>/cmd/enable_host_and_child_notifications

Sends the ENABLE_HOST_AND_CHILD_NOTIFICATIONS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_host_and_child_notifications.html for details.

=== POST /hosts/<name>/cmd/enable_host_check

Sends the ENABLE_HOST_CHECK command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_host_check.html for details.

=== POST /hosts/<name>/cmd/enable_host_event_handler

Sends the ENABLE_HOST_EVENT_HANDLER command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_host_event_handler.html for details.

=== POST /hosts/<name>/cmd/enable_host_flap_detection

Sends the ENABLE_HOST_FLAP_DETECTION command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_host_flap_detection.html for details.

=== POST /hosts/<name>/cmd/enable_host_notifications

Sends the ENABLE_HOST_NOTIFICATIONS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_host_notifications.html for details.

=== POST /hosts/<name>/cmd/enable_host_svc_checks

Sends the ENABLE_HOST_SVC_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_host_svc_checks.html for details.

=== POST /hosts/<name>/cmd/enable_host_svc_notifications

Sends the ENABLE_HOST_SVC_NOTIFICATIONS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_host_svc_notifications.html for details.

=== POST /hosts/<name>/cmd/enable_passive_host_checks

Sends the ENABLE_PASSIVE_HOST_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_passive_host_checks.html for details.

=== POST /hosts/<name>/cmd/process_host_check_result

Sends the PROCESS_HOST_CHECK_RESULT command.

Required arguments:

  * plugin_output

Optional arguments:

  * plugin_state
  * performance_data

See http://www.naemon.org/documentation/developer/externalcommands/process_host_check_result.html for details.

=== POST /hosts/<name>/cmd/remove_host_acknowledgement

Sends the REMOVE_HOST_ACKNOWLEDGEMENT command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/remove_host_acknowledgement.html for details.

=== POST /hosts/<name>/cmd/schedule_and_propagate_host_downtime

Sends the SCHEDULE_AND_PROPAGATE_HOST_DOWNTIME command.

Required arguments:

  * comment_data

Optional arguments:

  * start_time
  * end_time
  * fixed
  * triggered_by
  * duration
  * comment_author

See http://www.naemon.org/documentation/developer/externalcommands/schedule_and_propagate_host_downtime.html for details.

=== POST /hosts/<name>/cmd/schedule_and_propagate_triggered_host_downtime

Sends the SCHEDULE_AND_PROPAGATE_TRIGGERED_HOST_DOWNTIME command.

Required arguments:

  * comment_data

Optional arguments:

  * start_time
  * end_time
  * fixed
  * triggered_by
  * duration
  * comment_author

See http://www.naemon.org/documentation/developer/externalcommands/schedule_and_propagate_triggered_host_downtime.html for details.

=== POST /hosts/<name>/cmd/schedule_forced_host_check

Sends the SCHEDULE_FORCED_HOST_CHECK command.

Optional arguments:

  * start_time

See http://www.naemon.org/documentation/developer/externalcommands/schedule_forced_host_check.html for details.

=== POST /hosts/<name>/cmd/schedule_forced_host_svc_checks

Sends the SCHEDULE_FORCED_HOST_SVC_CHECKS command.

Optional arguments:

  * start_time

See http://www.naemon.org/documentation/developer/externalcommands/schedule_forced_host_svc_checks.html for details.

=== POST /hosts/<name>/cmd/schedule_host_check

Sends the SCHEDULE_HOST_CHECK command.

Optional arguments:

  * start_time

See http://www.naemon.org/documentation/developer/externalcommands/schedule_host_check.html for details.

=== POST /hosts/<name>/cmd/schedule_host_downtime

Sends the SCHEDULE_HOST_DOWNTIME command.

Required arguments:

  * comment_data

Optional arguments:

  * start_time
  * end_time
  * fixed
  * triggered_by
  * duration
  * comment_author

See http://www.naemon.org/documentation/developer/externalcommands/schedule_host_downtime.html for details.

=== POST /hosts/<name>/cmd/schedule_host_svc_checks

Sends the SCHEDULE_HOST_SVC_CHECKS command.

Optional arguments:

  * start_time

See http://www.naemon.org/documentation/developer/externalcommands/schedule_host_svc_checks.html for details.

=== POST /hosts/<name>/cmd/schedule_host_svc_downtime

Sends the SCHEDULE_HOST_SVC_DOWNTIME command.

Required arguments:

  * comment_data

Optional arguments:

  * start_time
  * end_time
  * fixed
  * triggered_by
  * duration
  * comment_author

See http://www.naemon.org/documentation/developer/externalcommands/schedule_host_svc_downtime.html for details.

=== POST /hosts/<name>/cmd/send_custom_host_notification

Sends the SEND_CUSTOM_HOST_NOTIFICATION command.

Required arguments:

  * comment_data

Optional arguments:

  * options
  * comment_author

See http://www.naemon.org/documentation/developer/externalcommands/send_custom_host_notification.html for details.

=== POST /hosts/<name>/cmd/start_obsessing_over_host

Sends the START_OBSESSING_OVER_HOST command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/start_obsessing_over_host.html for details.

=== POST /hosts/<name>/cmd/stop_obsessing_over_host

Sends the STOP_OBSESSING_OVER_HOST command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/stop_obsessing_over_host.html for details.

=== POST /servicegroups/<name>/cmd/...

external commands are documented in detail on a separate commands page.
list of supported commands:

 - link:rest_commands.html#post-servicegroups-name-cmd-disable-servicegroup-host-checks[disable_servicegroup_host_checks]
 - link:rest_commands.html#post-servicegroups-name-cmd-disable-servicegroup-host-notifications[disable_servicegroup_host_notifications]
 - link:rest_commands.html#post-servicegroups-name-cmd-disable-servicegroup-svc-checks[disable_servicegroup_svc_checks]
 - link:rest_commands.html#post-servicegroups-name-cmd-disable-servicegroup-svc-notifications[disable_servicegroup_svc_notifications]
 - link:rest_commands.html#post-servicegroups-name-cmd-enable-servicegroup-host-checks[enable_servicegroup_host_checks]
 - link:rest_commands.html#post-servicegroups-name-cmd-enable-servicegroup-host-notifications[enable_servicegroup_host_notifications]
 - link:rest_commands.html#post-servicegroups-name-cmd-enable-servicegroup-svc-checks[enable_servicegroup_svc_checks]
 - link:rest_commands.html#post-servicegroups-name-cmd-enable-servicegroup-svc-notifications[enable_servicegroup_svc_notifications]
 - link:rest_commands.html#post-servicegroups-name-cmd-schedule-servicegroup-host-downtime[schedule_servicegroup_host_downtime]
 - link:rest_commands.html#post-servicegroups-name-cmd-schedule-servicegroup-svc-downtime[schedule_servicegroup_svc_downtime]

=== POST /servicegroups/<name>/cmd/disable_servicegroup_host_checks

Sends the DISABLE_SERVICEGROUP_HOST_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_servicegroup_host_checks.html for details.

=== POST /servicegroups/<name>/cmd/disable_servicegroup_host_notifications

Sends the DISABLE_SERVICEGROUP_HOST_NOTIFICATIONS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_servicegroup_host_notifications.html for details.

=== POST /servicegroups/<name>/cmd/disable_servicegroup_svc_checks

Sends the DISABLE_SERVICEGROUP_SVC_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_servicegroup_svc_checks.html for details.

=== POST /servicegroups/<name>/cmd/disable_servicegroup_svc_notifications

Sends the DISABLE_SERVICEGROUP_SVC_NOTIFICATIONS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_servicegroup_svc_notifications.html for details.

=== POST /servicegroups/<name>/cmd/enable_servicegroup_host_checks

Sends the ENABLE_SERVICEGROUP_HOST_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_servicegroup_host_checks.html for details.

=== POST /servicegroups/<name>/cmd/enable_servicegroup_host_notifications

Sends the ENABLE_SERVICEGROUP_HOST_NOTIFICATIONS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_servicegroup_host_notifications.html for details.

=== POST /servicegroups/<name>/cmd/enable_servicegroup_svc_checks

Sends the ENABLE_SERVICEGROUP_SVC_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_servicegroup_svc_checks.html for details.

=== POST /servicegroups/<name>/cmd/enable_servicegroup_svc_notifications

Sends the ENABLE_SERVICEGROUP_SVC_NOTIFICATIONS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_servicegroup_svc_notifications.html for details.

=== POST /servicegroups/<name>/cmd/schedule_servicegroup_host_downtime

Sends the SCHEDULE_SERVICEGROUP_HOST_DOWNTIME command.

Required arguments:

  * comment_data

Optional arguments:

  * start_time
  * end_time
  * fixed
  * duration
  * comment_author

See http://www.naemon.org/documentation/developer/externalcommands/schedule_servicegroup_host_downtime.html for details.

=== POST /servicegroups/<name>/cmd/schedule_servicegroup_svc_downtime

Sends the SCHEDULE_SERVICEGROUP_SVC_DOWNTIME command.

Required arguments:

  * comment_data

Optional arguments:

  * start_time
  * end_time
  * fixed
  * duration
  * comment_author

See http://www.naemon.org/documentation/developer/externalcommands/schedule_servicegroup_svc_downtime.html for details.

=== POST /services/<host>/<service>/cmd/...

external commands are documented in detail on a separate commands page.
list of supported commands:

 - link:rest_commands.html#post-services-host-service-cmd-acknowledge-svc-problem[acknowledge_svc_problem]
 - link:rest_commands.html#post-services-host-service-cmd-acknowledge-svc-problem-expire[acknowledge_svc_problem_expire]
 - link:rest_commands.html#post-services-host-service-cmd-add-svc-comment[add_svc_comment]
 - link:rest_commands.html#post-services-host-service-cmd-change-svc-modattr[change_svc_modattr]
 - link:rest_commands.html#post-services-host-service-cmd-del-all-svc-comments[del_all_svc_comments]
 - link:rest_commands.html#post-services-host-service-cmd-delay-svc-notification[delay_svc_notification]
 - link:rest_commands.html#post-services-host-service-cmd-disable-passive-svc-checks[disable_passive_svc_checks]
 - link:rest_commands.html#post-services-host-service-cmd-disable-svc-check[disable_svc_check]
 - link:rest_commands.html#post-services-host-service-cmd-disable-svc-event-handler[disable_svc_event_handler]
 - link:rest_commands.html#post-services-host-service-cmd-disable-svc-flap-detection[disable_svc_flap_detection]
 - link:rest_commands.html#post-services-host-service-cmd-disable-svc-notifications[disable_svc_notifications]
 - link:rest_commands.html#post-services-host-service-cmd-enable-passive-svc-checks[enable_passive_svc_checks]
 - link:rest_commands.html#post-services-host-service-cmd-enable-svc-check[enable_svc_check]
 - link:rest_commands.html#post-services-host-service-cmd-enable-svc-event-handler[enable_svc_event_handler]
 - link:rest_commands.html#post-services-host-service-cmd-enable-svc-flap-detection[enable_svc_flap_detection]
 - link:rest_commands.html#post-services-host-service-cmd-enable-svc-notifications[enable_svc_notifications]
 - link:rest_commands.html#post-services-host-service-cmd-process-service-check-result[process_service_check_result]
 - link:rest_commands.html#post-services-host-service-cmd-remove-svc-acknowledgement[remove_svc_acknowledgement]
 - link:rest_commands.html#post-services-host-service-cmd-schedule-forced-svc-check[schedule_forced_svc_check]
 - link:rest_commands.html#post-services-host-service-cmd-schedule-svc-check[schedule_svc_check]
 - link:rest_commands.html#post-services-host-service-cmd-schedule-svc-downtime[schedule_svc_downtime]
 - link:rest_commands.html#post-services-host-service-cmd-send-custom-svc-notification[send_custom_svc_notification]
 - link:rest_commands.html#post-services-host-service-cmd-start-obsessing-over-svc[start_obsessing_over_svc]
 - link:rest_commands.html#post-services-host-service-cmd-stop-obsessing-over-svc[stop_obsessing_over_svc]

=== POST /services/<host>/<service>/cmd/acknowledge_svc_problem

Sends the ACKNOWLEDGE_SVC_PROBLEM command.

Required arguments:

  * comment_data

Optional arguments:

  * sticky_ack
  * send_notification
  * persistent_comment
  * comment_author

See http://www.naemon.org/documentation/developer/externalcommands/acknowledge_svc_problem.html for details.

=== POST /services/<host>/<service>/cmd/acknowledge_svc_problem_expire

Sends the ACKNOWLEDGE_SVC_PROBLEM_EXPIRE command.

Required arguments:

  * comment_data

Optional arguments:

  * sticky_ack
  * send_notification
  * persistent_comment
  * end_time
  * comment_author

See http://www.naemon.org/documentation/developer/externalcommands/acknowledge_svc_problem_expire.html for details.

=== POST /services/<host>/<service>/cmd/add_svc_comment

Sends the ADD_SVC_COMMENT command.

Required arguments:

  * comment_data

Optional arguments:

  * persistent_comment
  * comment_author

See http://www.naemon.org/documentation/developer/externalcommands/add_svc_comment.html for details.

=== POST /services/<host>/<service>/cmd/change_svc_modattr

Sends the CHANGE_SVC_MODATTR command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/change_svc_modattr.html for details.

=== POST /services/<host>/<service>/cmd/del_all_svc_comments

Sends the DEL_ALL_SVC_COMMENTS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/del_all_svc_comments.html for details.

=== POST /services/<host>/<service>/cmd/delay_svc_notification

Sends the DELAY_SVC_NOTIFICATION command.

Required arguments:

  * notification_time

See http://www.naemon.org/documentation/developer/externalcommands/delay_svc_notification.html for details.

=== POST /services/<host>/<service>/cmd/disable_passive_svc_checks

Sends the DISABLE_PASSIVE_SVC_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_passive_svc_checks.html for details.

=== POST /services/<host>/<service>/cmd/disable_svc_check

Sends the DISABLE_SVC_CHECK command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_svc_check.html for details.

=== POST /services/<host>/<service>/cmd/disable_svc_event_handler

Sends the DISABLE_SVC_EVENT_HANDLER command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_svc_event_handler.html for details.

=== POST /services/<host>/<service>/cmd/disable_svc_flap_detection

Sends the DISABLE_SVC_FLAP_DETECTION command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_svc_flap_detection.html for details.

=== POST /services/<host>/<service>/cmd/disable_svc_notifications

Sends the DISABLE_SVC_NOTIFICATIONS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_svc_notifications.html for details.

=== POST /services/<host>/<service>/cmd/enable_passive_svc_checks

Sends the ENABLE_PASSIVE_SVC_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_passive_svc_checks.html for details.

=== POST /services/<host>/<service>/cmd/enable_svc_check

Sends the ENABLE_SVC_CHECK command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_svc_check.html for details.

=== POST /services/<host>/<service>/cmd/enable_svc_event_handler

Sends the ENABLE_SVC_EVENT_HANDLER command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_svc_event_handler.html for details.

=== POST /services/<host>/<service>/cmd/enable_svc_flap_detection

Sends the ENABLE_SVC_FLAP_DETECTION command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_svc_flap_detection.html for details.

=== POST /services/<host>/<service>/cmd/enable_svc_notifications

Sends the ENABLE_SVC_NOTIFICATIONS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_svc_notifications.html for details.

=== POST /services/<host>/<service>/cmd/process_service_check_result

Sends the PROCESS_SERVICE_CHECK_RESULT command.

Required arguments:

  * plugin_output

Optional arguments:

  * plugin_state
  * performance_data

See http://www.naemon.org/documentation/developer/externalcommands/process_service_check_result.html for details.

=== POST /services/<host>/<service>/cmd/remove_svc_acknowledgement

Sends the REMOVE_SVC_ACKNOWLEDGEMENT command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/remove_svc_acknowledgement.html for details.

=== POST /services/<host>/<service>/cmd/schedule_forced_svc_check

Sends the SCHEDULE_FORCED_SVC_CHECK command.

Optional arguments:

  * start_time

See http://www.naemon.org/documentation/developer/externalcommands/schedule_forced_svc_check.html for details.

=== POST /services/<host>/<service>/cmd/schedule_svc_check

Sends the SCHEDULE_SVC_CHECK command.

Optional arguments:

  * start_time

See http://www.naemon.org/documentation/developer/externalcommands/schedule_svc_check.html for details.

=== POST /services/<host>/<service>/cmd/schedule_svc_downtime

Sends the SCHEDULE_SVC_DOWNTIME command.

Required arguments:

  * comment_data

Optional arguments:

  * start_time
  * end_time
  * fixed
  * triggered_by
  * duration
  * comment_author

See http://www.naemon.org/documentation/developer/externalcommands/schedule_svc_downtime.html for details.

=== POST /services/<host>/<service>/cmd/send_custom_svc_notification

Sends the SEND_CUSTOM_SVC_NOTIFICATION command.

Required arguments:

  * comment_data

Optional arguments:

  * options
  * comment_author

See http://www.naemon.org/documentation/developer/externalcommands/send_custom_svc_notification.html for details.

=== POST /services/<host>/<service>/cmd/start_obsessing_over_svc

Sends the START_OBSESSING_OVER_SVC command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/start_obsessing_over_svc.html for details.

=== POST /services/<host>/<service>/cmd/stop_obsessing_over_svc

Sends the STOP_OBSESSING_OVER_SVC command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/stop_obsessing_over_svc.html for details.

=== POST /system/cmd/...

external commands are documented in detail on a separate commands page.
list of supported commands:

 - link:rest_commands.html#post-system-cmd-del-host-comment[del_host_comment]
 - link:rest_commands.html#post-system-cmd-del-host-downtime[del_host_downtime]
 - link:rest_commands.html#post-system-cmd-del-svc-comment[del_svc_comment]
 - link:rest_commands.html#post-system-cmd-del-svc-downtime[del_svc_downtime]
 - link:rest_commands.html#post-system-cmd-disable-event-handlers[disable_event_handlers]
 - link:rest_commands.html#post-system-cmd-disable-failure-prediction[disable_failure_prediction]
 - link:rest_commands.html#post-system-cmd-disable-flap-detection[disable_flap_detection]
 - link:rest_commands.html#post-system-cmd-disable-notifications[disable_notifications]
 - link:rest_commands.html#post-system-cmd-disable-performance-data[disable_performance_data]
 - link:rest_commands.html#post-system-cmd-enable-event-handlers[enable_event_handlers]
 - link:rest_commands.html#post-system-cmd-enable-failure-prediction[enable_failure_prediction]
 - link:rest_commands.html#post-system-cmd-enable-flap-detection[enable_flap_detection]
 - link:rest_commands.html#post-system-cmd-enable-notifications[enable_notifications]
 - link:rest_commands.html#post-system-cmd-enable-performance-data[enable_performance_data]
 - link:rest_commands.html#post-system-cmd-restart-process[restart_process]
 - link:rest_commands.html#post-system-cmd-shutdown-process[shutdown_process]
 - link:rest_commands.html#post-system-cmd-start-accepting-passive-host-checks[start_accepting_passive_host_checks]
 - link:rest_commands.html#post-system-cmd-start-accepting-passive-svc-checks[start_accepting_passive_svc_checks]
 - link:rest_commands.html#post-system-cmd-start-executing-host-checks[start_executing_host_checks]
 - link:rest_commands.html#post-system-cmd-start-executing-svc-checks[start_executing_svc_checks]
 - link:rest_commands.html#post-system-cmd-start-obsessing-over-host-checks[start_obsessing_over_host_checks]
 - link:rest_commands.html#post-system-cmd-start-obsessing-over-svc-checks[start_obsessing_over_svc_checks]
 - link:rest_commands.html#post-system-cmd-stop-accepting-passive-host-checks[stop_accepting_passive_host_checks]
 - link:rest_commands.html#post-system-cmd-stop-accepting-passive-svc-checks[stop_accepting_passive_svc_checks]
 - link:rest_commands.html#post-system-cmd-stop-executing-host-checks[stop_executing_host_checks]
 - link:rest_commands.html#post-system-cmd-stop-executing-svc-checks[stop_executing_svc_checks]
 - link:rest_commands.html#post-system-cmd-stop-obsessing-over-host-checks[stop_obsessing_over_host_checks]
 - link:rest_commands.html#post-system-cmd-stop-obsessing-over-svc-checks[stop_obsessing_over_svc_checks]

=== POST /system/cmd/del_host_comment

Sends the DEL_HOST_COMMENT command.

Required arguments:

  * comment_id

See http://www.naemon.org/documentation/developer/externalcommands/del_host_comment.html for details.

=== POST /system/cmd/del_host_downtime

Sends the DEL_HOST_DOWNTIME command.

Required arguments:

  * downtime_id

See http://www.naemon.org/documentation/developer/externalcommands/del_host_downtime.html for details.

=== POST /system/cmd/del_svc_comment

Sends the DEL_SVC_COMMENT command.

Required arguments:

  * comment_id

See http://www.naemon.org/documentation/developer/externalcommands/del_svc_comment.html for details.

=== POST /system/cmd/del_svc_downtime

Sends the DEL_SVC_DOWNTIME command.

Required arguments:

  * downtime_id

See http://www.naemon.org/documentation/developer/externalcommands/del_svc_downtime.html for details.

=== POST /system/cmd/disable_event_handlers

Sends the DISABLE_EVENT_HANDLERS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_event_handlers.html for details.

=== POST /system/cmd/disable_failure_prediction

Sends the DISABLE_FAILURE_PREDICTION command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_failure_prediction.html for details.

=== POST /system/cmd/disable_flap_detection

Sends the DISABLE_FLAP_DETECTION command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_flap_detection.html for details.

=== POST /system/cmd/disable_notifications

Sends the DISABLE_NOTIFICATIONS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_notifications.html for details.

=== POST /system/cmd/disable_performance_data

Sends the DISABLE_PERFORMANCE_DATA command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/disable_performance_data.html for details.

=== POST /system/cmd/enable_event_handlers

Sends the ENABLE_EVENT_HANDLERS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_event_handlers.html for details.

=== POST /system/cmd/enable_failure_prediction

Sends the ENABLE_FAILURE_PREDICTION command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_failure_prediction.html for details.

=== POST /system/cmd/enable_flap_detection

Sends the ENABLE_FLAP_DETECTION command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_flap_detection.html for details.

=== POST /system/cmd/enable_notifications

Sends the ENABLE_NOTIFICATIONS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_notifications.html for details.

=== POST /system/cmd/enable_performance_data

Sends the ENABLE_PERFORMANCE_DATA command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/enable_performance_data.html for details.

=== POST /system/cmd/restart_process

Sends the RESTART_PROCESS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/restart_process.html for details.

=== POST /system/cmd/shutdown_process

Sends the SHUTDOWN_PROCESS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/shutdown_process.html for details.

=== POST /system/cmd/start_accepting_passive_host_checks

Sends the START_ACCEPTING_PASSIVE_HOST_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/start_accepting_passive_host_checks.html for details.

=== POST /system/cmd/start_accepting_passive_svc_checks

Sends the START_ACCEPTING_PASSIVE_SVC_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/start_accepting_passive_svc_checks.html for details.

=== POST /system/cmd/start_executing_host_checks

Sends the START_EXECUTING_HOST_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/start_executing_host_checks.html for details.

=== POST /system/cmd/start_executing_svc_checks

Sends the START_EXECUTING_SVC_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/start_executing_svc_checks.html for details.

=== POST /system/cmd/start_obsessing_over_host_checks

Sends the START_OBSESSING_OVER_HOST_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/start_obsessing_over_host_checks.html for details.

=== POST /system/cmd/start_obsessing_over_svc_checks

Sends the START_OBSESSING_OVER_SVC_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/start_obsessing_over_svc_checks.html for details.

=== POST /system/cmd/stop_accepting_passive_host_checks

Sends the STOP_ACCEPTING_PASSIVE_HOST_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/stop_accepting_passive_host_checks.html for details.

=== POST /system/cmd/stop_accepting_passive_svc_checks

Sends the STOP_ACCEPTING_PASSIVE_SVC_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/stop_accepting_passive_svc_checks.html for details.

=== POST /system/cmd/stop_executing_host_checks

Sends the STOP_EXECUTING_HOST_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/stop_executing_host_checks.html for details.

=== POST /system/cmd/stop_executing_svc_checks

Sends the STOP_EXECUTING_SVC_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/stop_executing_svc_checks.html for details.

=== POST /system/cmd/stop_obsessing_over_host_checks

Sends the STOP_OBSESSING_OVER_HOST_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/stop_obsessing_over_host_checks.html for details.

=== POST /system/cmd/stop_obsessing_over_svc_checks

Sends the STOP_OBSESSING_OVER_SVC_CHECKS command.

This command does not require any arguments.

See http://www.naemon.org/documentation/developer/externalcommands/stop_obsessing_over_svc_checks.html for details.

