---
- hosts: all
  tasks:
  - yum:
      name:
        - perl-Test-Harness
      state: present
  - shell: omd config demo set APACHE_MODE own
  - shell: omd config demo set CORE none
  - shell: omd config demo set PNP4NAGIOS off
  - shell: sudo su - demo -c "set_admin_password omd"
  - name: copy thruk_local.conf
    copy:
      src: /root/thruk_local.conf
      dest: /omd/sites/demo/etc/thruk/thruk_local.conf
      mode: 0644
      owner: demo
      group: demo
  - shell: sudo su - demo -c "cpanm -n File::ChangeNotify"
  - shell: sudo su - demo -c "cd ~/local/share && git clone git://github.com/sni/omd_utils.git"
  - shell: sudo su - demo -c "yes | ~/local/share/omd_utils/thruk_developer/install.sh /thruk"
