#!/usr/bin/perl

use strict;
use warnings;
use Thruk::Utils::CLI;
my $cli   = Thruk::Utils::CLI->new;
my $c     = $cli->get_c();
Thruk::Utils::Conf::set_object_model($c) or die("failed to set objects model");
my $hosts = $c->{'obj_db'}->get_objects_by_type('host');
printf("%-20s   %s\n", "Host", "File");
print("===========================================================\n");
for my $h (@{$hosts}) {
    printf("%-20s - %s:%d\n", $h->get_primary_name(), $h->{'file'}->{'path'}, $h->{'line'});
}
exit 0;

##############################################

=head1 NAME

list_hosts - Command Line Utility which lists hosts

=head1 SYNOPSIS

Usage: list_hosts

=head1 DESCRIPTION

This script lists all hosts

=head1 AUTHOR

2012, Sven Nierlein, <sven@nierlein.de>

=cut
