#!/usr/bin/perl

use warnings;
use strict;
use POSIX ":sys_wait_h";

my $timeout = shift @ARGV;
my $pid = fork();
if($pid) {
    exec(@ARGV);
} else {
    $SIG{'ALRM'} = sub {
        kill(9, $pid);
        exit 1;
    };
    alarm($timeout);
    while(waitpid($pid, 0) == -1) {}
    my $rc = $?>>8;
    exit($rc);
}
