version: '2'

services:
  omd:
    build: omd/
    ports:
        - "127.0.0.3:60080:80"
        - "127.0.0.3:60443:443"
        - "127.0.0.3:60557:6557"
    environment:
        - TZ=Europe/Berlin
        - PREFIX=omd
    volumes:
        - ../../../:/thruk:ro
        - .:/scenario:ro
