FROM  local/thruk-labs-rocky:nightly

COPY playbook.yml /root/ansible_dropin/
ENV  ANSIBLE_ROLES_PATH=/thruk/t/scenarios/_common/ansible/roles
COPY 1.rpt /root/
COPY 1.tab /root/
COPY 1.tsk /root/
COPY 1.tbp /root/
