---
- hosts: all
  roles:
    - role: common
    - role: local_tests
    - role: thruk_developer
  tasks:
  - name: "omd config change"
    shell: "omd config demo change"
    args:
      stdin: |
        APACHE_MODE=own
        LIVESTATUS_TCP=on
  - name: "install example.cfg"
    copy:
      src: /omd/sites/demo/share/doc/naemon/example.cfg
      dest: /omd/sites/demo/etc/naemon/conf.d/example.cfg
      owner: demo
      group: demo
  - name: "install skel files into demo site"
    shell: rsync -a --chown=demo:demo /root/ansible_dropin/skel/. /omd/sites/demo/.
  - name: "enable lmd"
    lineinfile:
      path: /omd/sites/demo/etc/thruk/thruk_local.d/lmd.conf
      regexp: '^#use_lmd_core'
      line: 'use_lmd_core=1'
