
/*
  Copyright (c) 2010, Nicolas Garcia Belmonte
  All rights reserved

  > Redistribution and use in source and binary forms, with or without
  > modification, are permitted provided that the following conditions are met:
  >      * Redistributions of source code must retain the above copyright
  >        notice, this list of conditions and the following disclaimer.
  >      * Redistributions in binary form must reproduce the above copyright
  >        notice, this list of conditions and the following disclaimer in the
  >        documentation and/or other materials provided with the distribution.
  >      * Neither the name of the organization nor the
  >        names of its contributors may be used to endorse or promote products
  >        derived from this software without specific prior written permission.
  >
  >  THIS SOFTWARE IS PROVIDED BY NICOLAS GARCIA BELMONTE ``AS IS'' AND ANY
  >  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  >  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  >  DISCLAIMED. IN NO EVENT SHALL NICOLAS GARCIA BELMONTE BE LIABLE FOR ANY
  >  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
  >  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
  >  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
  >  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  >  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
  >  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

 (function(){window.$jit=function(a){var a=a||window,c;for(c in $jit)$jit[c].$extend&&(a[c]=$jit[c])};$jit.version="2.0.0b";var g=function(a){return document.getElementById(a)};g.empty=function(){};g.extend=function(a,c){for(var b in c||{})a[b]=c[b];return a};g.lambda=function(a){return typeof a=="function"?a:function(){return a}};g.time=Date.now||function(){return+new Date};g.splat=function(a){var c=g.type(a);return c?c!="array"?[a]:a:[]};g.type=function(a){var c=g.type.s.call(a).match(/^\[object\s(.*)\]$/)[1].toLowerCase();
if(c!="object")return c;if(a&&a.$$family)return a.$$family;return a&&a.nodeName&&a.nodeType==1?"element":c};g.type.s=Object.prototype.toString;g.each=function(a,c){if(g.type(a)=="object")for(var b in a)c(a[b],b);else{b=0;for(var d=a.length;b<d;b++)c(a[b],b)}};g.indexOf=function(a,c){if(Array.indexOf)return a.indexOf(c);for(var b=0,d=a.length;b<d;b++)if(a[b]===c)return b;return-1};g.map=function(a,c){var b=[];g.each(a,function(a,e){b.push(c(a,e))});return b};g.reduce=function(a,c,b){var d=a.length;
if(d==0)return b;for(var e=arguments.length==3?b:a[--d];d--;)e=c(e,a[d]);return e};g.merge=function(){for(var a={},c=0,b=arguments.length;c<b;c++){var d=arguments[c];if(g.type(d)=="object")for(var e in d){var f=d[e],h=a[e];a[e]=h&&g.type(f)=="object"&&g.type(h)=="object"?g.merge(h,f):g.unlink(f)}}return a};g.unlink=function(a){var c;switch(g.type(a)){case "object":c={};for(var b in a)c[b]=g.unlink(a[b]);break;case "array":c=[];b=0;for(var d=a.length;b<d;b++)c[b]=g.unlink(a[b]);break;default:return a}return c};
g.zip=function(){if(arguments.length===0)return[];for(var a=0,c=[],b=arguments.length,d=arguments[0].length;a<d;a++){for(var e=0,f=[];e<b;e++)f.push(arguments[e][a]);c.push(f)}return c};g.rgbToHex=function(a,c){if(a.length<3)return null;if(a.length==4&&a[3]==0&&!c)return"transparent";for(var b=[],d=0;d<3;d++){var e=(a[d]-0).toString(16);b.push(e.length==1?"0"+e:e)}return c?b:"#"+b.join("")};g.hexToRgb=function(a){if(a.length!=7){a=a.match(/^#?(\w{1,2})(\w{1,2})(\w{1,2})$/);a.shift();if(a.length!=
3)return null;for(var c=[],b=0;b<3;b++){var d=a[b];d.length==1&&(d+=d);c.push(parseInt(d,16))}return c}else return a=parseInt(a.slice(1),16),[a>>16,a>>8&255,a&255]};g.destroy=function(a){g.clean(a);a.parentNode&&a.parentNode.removeChild(a);a.clearAttributes&&a.clearAttributes()};g.clean=function(a){for(var a=a.childNodes,c=0,b=a.length;c<b;c++)g.destroy(a[c])};g.addEvent=function(a,c,b){a.addEventListener?a.addEventListener(c,b,!1):a.attachEvent("on"+c,b)};g.addEvents=function(a,c){for(var b in c)g.addEvent(a,
b,c[b])};g.hasClass=function(a,c){return(" "+a.className+" ").indexOf(" "+c+" ")>-1};g.addClass=function(a,c){if(!g.hasClass(a,c))a.className=a.className+" "+c};g.removeClass=function(a,c){a.className=a.className.replace(RegExp("(^|\\s)"+c+"(?:\\s|$)"),"$1")};g.getPos=function(a){var c=function(a){for(var c={x:0,y:0};a&&!/^(?:body|html)$/i.test(a.tagName);)c.x+=a.offsetLeft,c.y+=a.offsetTop,a=a.offsetParent;return c}(a),a=function(a){for(var c={x:0,y:0};a&&!/^(?:body|html)$/i.test(a.tagName);)c.x+=
a.scrollLeft,c.y+=a.scrollTop,a=a.parentNode;return c}(a);return{x:c.x-a.x,y:c.y-a.y}};g.event={get:function(a,c){return a||(c||window).event},getWheel:function(a){return a.wheelDelta?a.wheelDelta/120:-(a.detail||0)/3},isRightClick:function(a){return a.which==3||a.button==2},getPos:function(a,c){var c=c||window,a=a||c.event,b=c.document,b=b.documentElement||b.body;a.touches&&a.touches.length&&(a=a.touches[0]);return{x:a.pageX||a.clientX+b.scrollLeft,y:a.pageY||a.clientY+b.scrollTop}},stop:function(a){a.stopPropagation&&
a.stopPropagation();a.cancelBubble=!0;a.preventDefault?a.preventDefault():a.returnValue=!1}};$jit.util=$jit.id=g;var i=function(a){var a=a||{},c=function(){for(var a in this)typeof this[a]!="function"&&(this[a]=g.unlink(this[a]));this.constructor=c;if(i.prototyping)return this;a=this.initialize?this.initialize.apply(this,arguments):this;this.$$family="class";return a},b;for(b in i.Mutators)a[b]&&(a=i.Mutators[b](a,a[b]),delete a[b]);g.extend(c,this);c.constructor=i;c.prototype=a;return c};i.Mutators=
{Implements:function(a,c){g.each(g.splat(c),function(c){i.prototyping=c;var c=typeof c=="function"?new c:c,d;for(d in c)d in a||(a[d]=c[d]);delete i.prototyping});return a}};g.extend(i,{inherit:function(a,c){for(var b in c){var d=c[b],e=a[b],f=g.type(d);e&&f=="function"?d!=e&&i.override(a,b,d):a[b]=f=="object"?g.merge(e,d):d}return a},override:function(a,c,b){var d=i.prototyping;d&&a[c]!=d[c]&&(d=null);a[c]=function(){var e=this.parent;this.parent=d?d[c]:a[c];var f=b.apply(this,arguments);this.parent=
e;return f}}});i.prototype.implement=function(){var a=this.prototype;g.each(Array.prototype.slice.call(arguments||[]),function(c){i.inherit(a,c)});return this};$jit.Class=i;$jit.json={prune:function(a,c){this.each(a,function(a,d){if(d==c&&a.children)delete a.children,a.children=[]})},getParent:function(a,c){if(a.id==c)return!1;var b=a.children;if(b&&b.length>0)for(var d=0;d<b.length;d++)if(b[d].id==c)return a;else{var e=this.getParent(b[d],c);if(e)return e}return!1},getSubtree:function(a,c){if(a.id==
c)return a;for(var b=0,d=a.children;b<d.length;b++){var e=this.getSubtree(d[b],c);if(e!=null)return e}return null},eachLevel:function(a,c,b,d){if(c<=b&&(d(a,c),a.children))for(var e=0,a=a.children;e<a.length;e++)this.eachLevel(a[e],c+1,b,d)},each:function(a,c){this.eachLevel(a,0,Number.MAX_VALUE,c)}};$jit.Trans={$extend:!0,linear:function(a){return a}};var x=$jit.Trans;(function(){var a=function(a,b){b=g.splat(b);return g.extend(a,{easeIn:function(d){return a(d,b)},easeOut:function(d){return 1-a(1-
d,b)},easeInOut:function(d){return d<=0.5?a(2*d,b)/2:(2-a(2*(1-d),b))/2}})};g.each({Pow:function(a,b){return Math.pow(a,b[0]||6)},Expo:function(a){return Math.pow(2,8*(a-1))},Circ:function(a){return 1-Math.sin(Math.acos(a))},Sine:function(a){return 1-Math.sin((1-a)*Math.PI/2)},Back:function(a,b){b=b[0]||1.618;return Math.pow(a,2)*((b+1)*a-b)},Bounce:function(a){for(var b,d=0,e=1;;d+=e,e/=2)if(a>=(7-4*d)/11){b=e*e-Math.pow((11-6*d-11*a)/4,2);break}return b},Elastic:function(a,b){return Math.pow(2,
10*--a)*Math.cos(20*a*Math.PI*(b[0]||1)/3)}},function(c,b){x[b]=a(c)});g.each(["Quad","Cubic","Quart","Quint"],function(c,b){x[c]=a(function(a){return Math.pow(a,[b+2])})})})();var z=new i({initialize:function(a){this.setOptions(a)},setOptions:function(a){this.opt=g.merge({duration:2500,fps:40,transition:x.Quart.easeInOut,compute:g.empty,complete:g.empty,link:"ignore"},a||{});return this},step:function(){var a=g.time(),c=this.opt;a<this.time+c.duration?(a=c.transition((a-this.time)/c.duration),c.compute(a)):
(this.timer=clearInterval(this.timer),c.compute(1),c.complete())},start:function(){if(!this.check())return this;this.time=0;this.startTimer();return this},startTimer:function(){var a=this,c=this.opt.fps;if(this.timer)return!1;this.time=g.time()-this.time;this.timer=setInterval(function(){a.step()},Math.round(1E3/c));return!0},pause:function(){this.stopTimer();return this},resume:function(){this.startTimer();return this},stopTimer:function(){if(!this.timer)return!1;this.time=g.time()-this.time;this.timer=
clearInterval(this.timer);return!0},check:function(){if(!this.timer)return!0;if(this.opt.link=="cancel")return this.stopTimer(),!0;return!1}}),q=function(){for(var a=arguments,c=0,b=a.length,d={};c<b;c++){var e=q[a[c]];e.$extend?g.extend(d,e):d[a[c]]=e}return d};q.Canvas={$extend:!0,injectInto:"id",width:!1,height:!1,useCanvas:!1,withLabels:!0,background:!1};q.Node={$extend:!1,overridable:!1,type:"circle",color:"#ccb",alpha:1,dim:3,height:20,width:90,autoHeight:!1,autoWidth:!1,lineWidth:1,transform:!0,
align:"center",angularWidth:1,span:1,CanvasStyles:{}};q.Edge={$extend:!1,overridable:!1,type:"line",color:"#ccb",lineWidth:1,dim:15,alpha:1,epsilon:7,CanvasStyles:{}};q.Fx={$extend:!0,fps:40,duration:2500,transition:$jit.Trans.Quart.easeInOut,clearCanvas:!0};q.Label={$extend:!1,overridable:!1,type:"HTML",style:" ",size:10,family:"sans-serif",textAlign:"center",textBaseline:"alphabetic",color:"#fff"};q.Tips={$extend:!1,enable:!1,type:"auto",offsetX:20,offsetY:20,force:!1,onShow:g.empty,onHide:g.empty};
q.NodeStyles={$extend:!1,enable:!1,type:"auto",stylesHover:!1,stylesClick:!1};q.Events={$extend:!1,enable:!1,enableForEdges:!1,type:"auto",onClick:g.empty,onRightClick:g.empty,onMouseMove:g.empty,onMouseEnter:g.empty,onMouseLeave:g.empty,onDragStart:g.empty,onDragMove:g.empty,onDragCancel:g.empty,onDragEnd:g.empty,onTouchStart:g.empty,onTouchMove:g.empty,onTouchEnd:g.empty,onMouseWheel:g.empty};q.Navigation={$extend:!1,enable:!1,type:"auto",panning:!1,zooming:!1};q.Controller={$extend:!0,onBeforeCompute:g.empty,
onAfterCompute:g.empty,onCreateLabel:g.empty,onPlaceLabel:g.empty,onComplete:g.empty,onBeforePlotLine:g.empty,onAfterPlotLine:g.empty,onBeforePlotNode:g.empty,onAfterPlotNode:g.empty,request:!1};var t={initialize:function(a,c){this.viz=c;this.canvas=c.canvas;this.config=c.config[a];this.nodeTypes=c.fx.nodeTypes;var b=this.config.type;this.labelContainer=(this.dom=b=="auto"?c.config.Label.type!="Native":b!="Native")&&c.labels.getLabelContainer();this.isEnabled()&&this.initializePost()},initializePost:g.empty,
setAsProperty:g.lambda(!1),isEnabled:function(){return this.config.enable},isLabel:function(a,c){var a=g.event.get(a,c),b=this.labelContainer,d=a.target||a.srcElement;if(d&&d.parentNode==b)return d;return!1}},p={onMouseUp:g.empty,onMouseDown:g.empty,onMouseMove:g.empty,onMouseOver:g.empty,onMouseOut:g.empty,onMouseWheel:g.empty,onTouchStart:g.empty,onTouchMove:g.empty,onTouchEnd:g.empty,onTouchCancel:g.empty},C=new i({initialize:function(a){this.viz=a;this.canvas=a.canvas;this.edge=this.node=!1;this.registeredObjects=
[];this.attachEvents()},attachEvents:function(){var a=this.canvas.getElement(),c=this;a.oncontextmenu=g.lambda(!1);g.addEvents(a,{mouseup:function(a,b){var f=g.event.get(a,b);c.handleEvent("MouseUp",a,b,c.makeEventObject(a,b),g.event.isRightClick(f))},mousedown:function(a,b){var f=g.event.get(a,b);c.handleEvent("MouseDown",a,b,c.makeEventObject(a,b),g.event.isRightClick(f))},mousemove:function(a,b){c.handleEvent("MouseMove",a,b,c.makeEventObject(a,b))},mouseover:function(a,b){c.handleEvent("MouseOver",
a,b,c.makeEventObject(a,b))},mouseout:function(a,b){c.handleEvent("MouseOut",a,b,c.makeEventObject(a,b))},touchstart:function(a,b){c.handleEvent("TouchStart",a,b,c.makeEventObject(a,b))},touchmove:function(a,b){c.handleEvent("TouchMove",a,b,c.makeEventObject(a,b))},touchend:function(a,b){c.handleEvent("TouchEnd",a,b,c.makeEventObject(a,b))}});var b=function(a,b){var f=g.event.get(a,b),f=g.event.getWheel(f);c.handleEvent("MouseWheel",a,b,f)};!document.getBoxObjectFor&&window.mozInnerScreenX==null?
g.addEvent(a,"mousewheel",b):a.addEventListener("DOMMouseScroll",b,!1)},register:function(a){this.registeredObjects.push(a)},handleEvent:function(){for(var a=Array.prototype.slice.call(arguments),c=a.shift(),b=0,d=this.registeredObjects,e=d.length;b<e;b++)d[b]["on"+c].apply(d[b],a)},makeEventObject:function(a,c){var b=this,d=this.viz.graph,e=this.viz.fx,f=e.nodeTypes,h=e.edgeTypes;return{pos:!1,node:!1,edge:!1,contains:!1,getNodeCalled:!1,getEdgeCalled:!1,getPos:function(){var d=b.viz.canvas,e=d.getSize(),
f=d.getPos(),h=d.translateOffsetX,w=d.translateOffsetY,i=d.scaleOffsetX,d=d.scaleOffsetY,k=g.event.getPos(a,c);return this.pos={x:(k.x-f.x-e.width/2-h)*1/i,y:(k.y-f.y-e.height/2-w)*1/d}},getNode:function(){if(this.getNodeCalled)return this.node;this.getNodeCalled=!0;for(var a in d.nodes){var c=d.nodes[a],h=c&&f[c.getData("type")];if(h=h&&h.contains&&h.contains.call(e,c,this.getPos()))return this.contains=h,b.node=this.node=c}return b.node=this.node=!1},getEdge:function(){if(this.getEdgeCalled)return this.edge;
this.getEdgeCalled=!0;var a={},c;for(c in d.edges){var f=d.edges[c];a[c]=!0;for(var g in f)if(!(g in a)){var w=f[g],i=w&&h[w.getData("type")];if(i=i&&i.contains&&i.contains.call(e,w,this.getPos()))return this.contains=i,b.edge=this.edge=w}}return b.edge=this.edge=!1},getContains:function(){if(this.getNodeCalled)return this.contains;this.getNode();return this.contains}}}}),s={initializeExtras:function(){var a=new C(this),c=this;g.each(["NodeStyles","Tips","Navigation","Events"],function(b){var d=new s.Classes[b](b,
c);d.isEnabled()&&a.register(d);d.setAsProperty()&&(c[b.toLowerCase()]=d)})},Classes:{}};s.Classes.Events=new i({Implements:[t,p],initializePost:function(){this.fx=this.viz.fx;this.ntypes=this.viz.fx.nodeTypes;this.etypes=this.viz.fx.edgeTypes;this.moved=this.touchMoved=this.touched=this.pressed=this.hovered=!1},setAsProperty:g.lambda(!0),onMouseUp:function(a,c,b,d){a=g.event.get(a,c);if(!this.moved)if(d)this.config.onRightClick(this.hovered,b,a);else this.config.onClick(this.pressed,b,a);if(this.pressed){if(this.moved)this.config.onDragEnd(this.pressed,
b,a);else this.config.onDragCancel(this.pressed,b,a);this.pressed=this.moved=!1}},onMouseOut:function(a,c,b){var d=g.event.get(a,c),e;if(this.dom&&(e=this.isLabel(a,c)))this.config.onMouseLeave(this.viz.graph.getNode(e.id),b,d),this.hovered=!1;else{a=d.relatedTarget;for(c=this.canvas.getElement();a&&a.parentNode;){if(c==a.parentNode)return;a=a.parentNode}if(this.hovered)this.config.onMouseLeave(this.hovered,b,d),this.hovered=!1}},onMouseOver:function(a,c,b){var d=g.event.get(a,c),e;if(this.dom&&(e=
this.isLabel(a,c)))this.hovered=this.viz.graph.getNode(e.id),this.config.onMouseEnter(this.hovered,b,d)},onMouseMove:function(a,c,b){a=g.event.get(a,c);if(this.pressed)this.moved=!0,this.config.onDragMove(this.pressed,b,a);else if(this.dom)this.config.onMouseMove(this.hovered,b,a);else{if(this.hovered){var c=this.hovered,d=c.nodeFrom?this.etypes[c.getData("type")]:this.ntypes[c.getData("type")];if(d&&d.contains&&d.contains.call(this.fx,c,b.getPos())){this.config.onMouseMove(c,b,a);return}else this.config.onMouseLeave(c,
b,a),this.hovered=!1}if(this.hovered=b.getNode()||this.config.enableForEdges&&b.getEdge())this.config.onMouseEnter(this.hovered,b,a);else this.config.onMouseMove(!1,b,a)}},onMouseWheel:function(a,c,b){this.config.onMouseWheel(b,g.event.get(a,c))},onMouseDown:function(a,c,b){a=g.event.get(a,c);this.pressed=b.getNode()||this.config.enableForEdges&&b.getEdge();this.config.onDragStart(this.pressed,b,a)},onTouchStart:function(a,c,b){a=g.event.get(a,c);this.touched=b.getNode()||this.config.enableForEdges&&
b.getEdge();this.config.onTouchStart(this.touched,b,a)},onTouchMove:function(a,c,b){a=g.event.get(a,c);if(this.touched)this.touchMoved=!0,this.config.onTouchMove(this.touched,b,a)},onTouchEnd:function(a,c,b){a=g.event.get(a,c);if(this.touched){if(this.touchMoved)this.config.onTouchEnd(this.touched,b,a);else this.config.onTouchCancel(this.touched,b,a);this.touched=this.touchMoved=!1}}});s.Classes.Tips=new i({Implements:[t,p],initializePost:function(){if(document.body){var a=g("_tooltip")||document.createElement("div");
a.id="_tooltip";a.className="tip";g.extend(a.style,{position:"absolute",display:"none",zIndex:13E3});document.body.appendChild(a);this.tip=a;this.node=!1}},setAsProperty:g.lambda(!0),onMouseOut:function(a,c){if(this.dom&&this.isLabel(a,c))this.hide(!0);else{for(var b=a.relatedTarget,d=this.canvas.getElement();b&&b.parentNode;){if(d==b.parentNode)return;b=b.parentNode}this.hide(!1)}},onMouseOver:function(a,c){var b;if(this.dom&&(b=this.isLabel(a,c)))this.node=this.viz.graph.getNode(b.id),this.config.onShow(this.tip,
this.node,b)},onMouseMove:function(a,c,b){this.dom&&this.isLabel(a,c)&&this.setTooltipPosition(g.event.getPos(a,c));if(!this.dom){var d=b.getNode();if(d){if(this.config.force||!this.node||this.node.id!=d.id)this.node=d,this.config.onShow(this.tip,d,b.getContains());this.setTooltipPosition(g.event.getPos(a,c))}else this.hide(!0)}},setTooltipPosition:function(a){var c=this.tip,b=c.style,d=this.config;b.display="";var e={height:document.body.clientHeight,width:document.body.clientWidth},c={width:c.offsetWidth,
height:c.offsetHeight},f=d.offsetX,d=d.offsetY;b.top=(a.y+d+c.height>e.height?a.y-c.height-d:a.y+d)+"px";b.left=(a.x+c.width+f>e.width?a.x-c.width-f:a.x+f)+"px"},hide:function(a){this.tip.style.display="none";a&&this.config.onHide()}});s.Classes.NodeStyles=new i({Implements:[t,p],initializePost:function(){this.fx=this.viz.fx;this.types=this.viz.fx.nodeTypes;this.nStyles=this.config;this.nodeStylesOnHover=this.nStyles.stylesHover;this.nodeStylesOnClick=this.nStyles.stylesClick;this.hoveredNode=!1;
this.fx.nodeFxAnimation=new z;this.move=this.down=!1},onMouseOut:function(a,c){this.down=this.move=!1;if(this.hoveredNode){this.dom&&this.isLabel(a,c)&&this.toggleStylesOnHover(this.hoveredNode,!1);for(var b=a.relatedTarget,d=this.canvas.getElement();b&&b.parentNode;){if(d==b.parentNode)return;b=b.parentNode}this.toggleStylesOnHover(this.hoveredNode,!1);this.hoveredNode=!1}},onMouseOver:function(a,c){var b;if(this.dom&&(b=this.isLabel(a,c)))if(b=this.viz.graph.getNode(b.id),!b.selected)this.hoveredNode=
b,this.toggleStylesOnHover(this.hoveredNode,!0)},onMouseDown:function(a,c,b,d){if(!d){var e;if(this.dom&&(e=this.isLabel(a,c)))this.down=this.viz.graph.getNode(e.id);else if(!this.dom)this.down=b.getNode();this.move=!1}},onMouseUp:function(a,c,b,d){if(!d){if(!this.move)this.onClick(b.getNode());this.down=this.move=!1}},getRestoredStyles:function(a,c){var b={},d=this["nodeStylesOn"+c],e;for(e in d)b[e]=a.styles["$"+e];return b},toggleStylesOnHover:function(a,c){this.nodeStylesOnHover&&this.toggleStylesOn("Hover",
a,c)},toggleStylesOnClick:function(a,c){this.nodeStylesOnClick&&this.toggleStylesOn("Click",a,c)},toggleStylesOn:function(a,c,b){var d=this.viz;if(b){if(!c.styles)c.styles=g.merge(c.data,{});for(var e in this["nodeStylesOn"+a])b="$"+e,b in c.styles||(c.styles[b]=c.getData(e));d.fx.nodeFx(g.extend({elements:{id:c.id,properties:this["nodeStylesOn"+a]},transition:x.Quart.easeOut,duration:300,fps:40},this.config))}else a=this.getRestoredStyles(c,a),d.fx.nodeFx(g.extend({elements:{id:c.id,properties:a},
transition:x.Quart.easeOut,duration:300,fps:40},this.config))},onClick:function(a){if(a){var c=this.nodeStylesOnClick;if(c)a.selected?(this.toggleStylesOnClick(a,!1),delete a.selected):(this.viz.graph.eachNode(function(a){if(a.selected){for(var d in c)a.setData(d,a.styles["$"+d],"end");delete a.selected}}),this.toggleStylesOnClick(a,!0),a.selected=!0,delete a.hovered,this.hoveredNode=!1)}},onMouseMove:function(a,c,b){if(this.down)this.move=!0;if(!this.dom||!this.isLabel(a,c)){var d=this.nodeStylesOnHover;
if(d&&!this.dom){if(this.hoveredNode&&(a=this.types[this.hoveredNode.getData("type")])&&a.contains&&a.contains.call(this.fx,this.hoveredNode,b.getPos()))return;b=b.getNode();if((this.hoveredNode||b)&&!b.hovered)if(b&&!b.selected)this.fx.nodeFxAnimation.stopTimer(),this.viz.graph.eachNode(function(a){if(a.hovered&&!a.selected){for(var c in d)a.setData(c,a.styles["$"+c],"end");delete a.hovered}}),b.hovered=!0,this.hoveredNode=b,this.toggleStylesOnHover(b,!0);else if(this.hoveredNode&&!this.hoveredNode.selected)this.fx.nodeFxAnimation.stopTimer(),
this.toggleStylesOnHover(this.hoveredNode,!1),delete this.hoveredNode.hovered,this.hoveredNode=!1}}}});s.Classes.Navigation=new i({Implements:[t,p],initializePost:function(){this.pressed=this.pos=!1},onMouseWheel:function(a,c,b){this.config.zooming&&(g.event.stop(g.event.get(a,c)),a=1+b*(this.config.zooming/1E3),this.canvas.scale(a,a))},onMouseDown:function(a,c,b){if(this.config.panning&&!(this.config.panning=="avoid nodes"&&b.getNode())){this.pressed=!0;this.pos=b.getPos();var a=this.canvas,c=a.translateOffsetX,
b=a.translateOffsetY,d=a.scaleOffsetY;this.pos.x*=a.scaleOffsetX;this.pos.x+=c;this.pos.y*=d;this.pos.y+=b}},onMouseMove:function(a,c,b){if(this.config.panning&&this.pressed&&!(this.config.panning=="avoid nodes"&&b.getNode())){var a=this.pos,b=b.getPos(),d=this.canvas,e=d.translateOffsetX,f=d.translateOffsetY,c=d.scaleOffsetX,d=d.scaleOffsetY;b.x*=c;b.y*=d;b.x+=e;b.y+=f;e=b.x-a.x;a=b.y-a.y;this.pos=b;this.canvas.translate(e*1/c,a*1/d)}},onMouseUp:function(){if(this.config.panning)this.pressed=!1}});
var u;(function(){function a(a,c){var f=document.createElement(a),h;for(h in c)typeof c[h]=="object"?g.extend(f[h],c[h]):f[h]=c[h];a=="canvas"&&!b&&G_vmlCanvasManager&&(f=G_vmlCanvasManager.initElement(document.body.appendChild(f)));return f}var c=typeof HTMLCanvasElement,b=c=="object"||c=="function";$jit.Canvas=u=new i({canvases:[],pos:!1,element:!1,labelContainer:!1,translateOffsetX:0,translateOffsetY:0,scaleOffsetX:1,scaleOffsetY:1,initialize:function(c,b){this.viz=c;this.opt=b;var f=g.type(b.injectInto)==
"string"?b.injectInto:b.injectInto.id,h=f+"-label",n=g(f),j=b.width||n.offsetWidth,v=b.height||n.offsetHeight;this.id=f;var m={injectInto:f,width:j,height:v};this.element=a("div",{id:f+"-canvaswidget",style:{position:"relative",width:j+"px",height:v+"px"}});this.labelContainer=this.createLabelContainer(b.Label.type,h,m);this.canvases.push(new u.Base({config:g.extend({idSuffix:"-canvas"},m),plot:function(){c.fx.plot()},resize:function(){c.refresh()}}));if(f=b.background)m=new u.Background[f.type](c,
g.extend(f,m)),this.canvases.push(new u.Base(m));for(m=this.canvases.length;m--;)this.element.appendChild(this.canvases[m].canvas),m>0&&this.canvases[m].plot();this.element.appendChild(this.labelContainer);n.appendChild(this.element);var w=null,i=this;g.addEvent(window,"scroll",function(){clearTimeout(w);w=setTimeout(function(){i.getPos(!0)},500)})},getCtx:function(a){return this.canvases[a||0].getCtx()},getConfig:function(){return this.opt},getElement:function(){return this.element},getSize:function(a){return this.canvases[a||
0].getSize()},resize:function(a,c){this.getPos(!0);this.translateOffsetX=this.translateOffsetY=0;this.scaleOffsetX=this.scaleOffsetY=1;for(var b=0,h=this.canvases.length;b<h;b++)this.canvases[b].resize(a,c);b=this.element.style;b.width=a+"px";b.height=c+"px";if(this.labelContainer)this.labelContainer.style.width=a+"px"},translate:function(a,c,b){this.translateOffsetX+=a*this.scaleOffsetX;this.translateOffsetY+=c*this.scaleOffsetY;for(var h=0,g=this.canvases.length;h<g;h++)this.canvases[h].translate(a,
c,b)},scale:function(a,c){var b=this.scaleOffsetX*a,h=this.scaleOffsetY*c,g=this.translateOffsetX*(a-1)/b,j=this.translateOffsetY*(c-1)/h;this.scaleOffsetX=b;this.scaleOffsetY=h;b=0;for(h=this.canvases.length;b<h;b++)this.canvases[b].scale(a,c,!0);this.translate(g,j,!1)},getPos:function(a){if(a||!this.pos)return this.pos=g.getPos(this.getElement());return this.pos},clear:function(a){this.canvases[a||0].clear()},path:function(a,c){var b=this.canvases[0].getCtx();b.beginPath();c(b);b[a]();b.closePath()},
createLabelContainer:function(c,b,f){if(c=="HTML"||c=="Native")return a("div",{id:b,style:{overflow:"visible",position:"absolute",top:0,left:0,width:f.width+"px",height:0}});else if(c=="SVG"){c=document.createElementNS("http://www.w3.org/2000/svg","svg:svg");c.setAttribute("width",f.width);c.setAttribute("height",f.height);var h=c.style;h.position="absolute";h.left=h.top="0px";h=document.createElementNS("http://www.w3.org/2000/svg","svg:g");h.setAttribute("width",f.width);h.setAttribute("height",
f.height);h.setAttribute("x",0);h.setAttribute("y",0);h.setAttribute("id",b);c.appendChild(h);return c}}});u.Base=new i({translateOffsetX:0,translateOffsetY:0,scaleOffsetX:1,scaleOffsetY:1,initialize:function(a){this.viz=a;this.opt=a.config;this.size=!1;this.createCanvas();this.translateToCenter()},createCanvas:function(){var c=this.opt,b=c.width,f=c.height;this.canvas=a("canvas",{id:c.injectInto+c.idSuffix,width:b,height:f,style:{position:"absolute",top:0,left:0,width:b+"px",height:f+"px"}})},getCtx:function(){if(!this.ctx)return this.ctx=
this.canvas.getContext("2d");return this.ctx},getSize:function(){if(this.size)return this.size;var a=this.canvas;return this.size={width:a.width,height:a.height}},translateToCenter:function(a){var c=this.getSize(),b=a?c.width-a.width-this.translateOffsetX*2:c.width;height=a?c.height-a.height-this.translateOffsetY*2:c.height;c=this.getCtx();a&&c.scale(1/this.scaleOffsetX,1/this.scaleOffsetY);c.translate(b/2,height/2)},resize:function(a,c){var f=this.getSize(),h=this.canvas,g=h.style;this.size=!1;h.width=
a;h.height=c;g.width=a+"px";g.height=c+"px";b?this.translateToCenter():this.translateToCenter(f);this.translateOffsetX=this.translateOffsetY=0;this.scaleOffsetX=this.scaleOffsetY=1;this.clear();this.viz.resize(a,c,this)},translate:function(a,c,b){var h=this.scaleOffsetY;this.translateOffsetX+=a*this.scaleOffsetX;this.translateOffsetY+=c*h;this.getCtx().translate(a,c);!b&&this.plot()},scale:function(a,c,b){this.scaleOffsetX*=a;this.scaleOffsetY*=c;this.getCtx().scale(a,c);!b&&this.plot()},clear:function(){var a=
this.getSize(),c=this.translateOffsetX,b=this.translateOffsetY,h=this.scaleOffsetX,g=this.scaleOffsetY;this.getCtx().clearRect((-a.width/2-c)*1/h,(-a.height/2-b)*1/g,a.width*1/h,a.height*1/g)},plot:function(){this.clear();this.viz.plot(this)}});u.Background={};u.Background.Circles=new i({initialize:function(a,c){this.viz=a;this.config=g.merge({idSuffix:"-bkcanvas",levelDistance:100,numberOfCircles:6,CanvasStyles:{},offset:0},c)},resize:function(a,c,b){this.plot(b)},plot:function(a){var a=a.getCtx(),
c=this.config,b=c.CanvasStyles,h;for(h in b)a[h]=b[h];h=c.numberOfCircles;c=c.levelDistance;for(b=1;b<=h;b++)a.beginPath(),a.arc(0,0,c*b,0,2*Math.PI,!1),a.stroke(),a.closePath()}})})();var r=function(a,c){this.theta=a;this.rho=c};$jit.Polar=r;r.prototype={getc:function(a){return this.toComplex(a)},getp:function(){return this},set:function(a){a=a.getp();this.theta=a.theta;this.rho=a.rho},setc:function(a,c){this.rho=Math.sqrt(a*a+c*c);this.theta=Math.atan2(c,a);this.theta<0&&(this.theta+=Math.PI*2)},
setp:function(a,c){this.theta=a;this.rho=c},clone:function(){return new r(this.theta,this.rho)},toComplex:function(a){var c=Math.cos(this.theta)*this.rho,b=Math.sin(this.theta)*this.rho;if(a)return{x:c,y:b};return new o(c,b)},add:function(a){return new r(this.theta+a.theta,this.rho+a.rho)},scale:function(a){return new r(this.theta,this.rho*a)},equals:function(a){return this.theta==a.theta&&this.rho==a.rho},$add:function(a){this.theta+=a.theta;this.rho+=a.rho;return this},$madd:function(a){this.theta=
(this.theta+a.theta)%(Math.PI*2);this.rho+=a.rho;return this},$scale:function(a){this.rho*=a;return this},interpolate:function(a,c){var b=Math.PI,d=b*2,e=function(a){return a<0?a%d+d:a%d},f=this.theta,h=a.theta,g=Math.abs(f-h);return{theta:g==b?f>h?e(h+(f-d-h)*c):e(h-d+(f-h)*c):g>=b?f>h?e(h+(f-d-h)*c):e(h-d+(f-(h-d))*c):e(h+(f-h)*c),rho:(this.rho-a.rho)*c+a.rho}}};r.KER=new r(0,0);var o=function(a,c){this.x=a;this.y=c};$jit.Complex=o;o.prototype={getc:function(){return this},getp:function(a){return this.toPolar(a)},
set:function(a){a=a.getc(!0);this.x=a.x;this.y=a.y},setc:function(a,c){this.x=a;this.y=c},setp:function(a,c){this.x=Math.cos(a)*c;this.y=Math.sin(a)*c},clone:function(){return new o(this.x,this.y)},toPolar:function(a){var c=this.norm(),b=Math.atan2(this.y,this.x);b<0&&(b+=Math.PI*2);if(a)return{theta:b,rho:c};return new r(b,c)},norm:function(){return Math.sqrt(this.squaredNorm())},squaredNorm:function(){return this.x*this.x+this.y*this.y},add:function(a){return new o(this.x+a.x,this.y+a.y)},prod:function(a){return new o(this.x*
a.x-this.y*a.y,this.y*a.x+this.x*a.y)},conjugate:function(){return new o(this.x,-this.y)},scale:function(a){return new o(this.x*a,this.y*a)},equals:function(a){return this.x==a.x&&this.y==a.y},$add:function(a){this.x+=a.x;this.y+=a.y;return this},$prod:function(a){var c=this.x,b=this.y;this.x=c*a.x-b*a.y;this.y=b*a.x+c*a.y;return this},$conjugate:function(){this.y=-this.y;return this},$scale:function(a){this.x*=a;this.y*=a;return this},$div:function(a){var c=this.x,b=this.y,d=a.squaredNorm();this.x=
c*a.x+b*a.y;this.y=b*a.x-c*a.y;return this.$scale(1/d)}};o.KER=new o(0,0);$jit.Graph=new i({initialize:function(a,c,b,d){this.Node=c;this.Edge=b;this.Label=d;this.opt=g.merge({complex:!1,Node:{}},a||{});this.nodes={};this.edges={};var e=this;this.nodeList={};for(var f in y)e.nodeList[f]=function(a){return function(){var c=Array.prototype.slice.call(arguments);e.eachNode(function(b){b[a].apply(b,c)})}}(f)},getNode:function(a){if(this.hasNode(a))return this.nodes[a];return!1},getByName:function(a){for(var c in this.nodes){var b=
this.nodes[c];if(b.name==a)return b}return!1},getAdjacence:function(a,c){if(a in this.edges)return this.edges[a][c];return!1},addNode:function(a){if(!this.nodes[a.id]){var c=this.edges[a.id]={};this.nodes[a.id]=new k.Node(g.extend({id:a.id,name:a.name,data:g.merge(a.data||{},{}),adjacencies:c},this.opt.Node),this.opt.complex,this.Node,this.Edge,this.Label)}return this.nodes[a.id]},addAdjacence:function(a,c,b){this.hasNode(a.id)||this.addNode(a);this.hasNode(c.id)||this.addNode(c);a=this.nodes[a.id];
c=this.nodes[c.id];if(!a.adjacentTo(c)){var d=this.edges[a.id]=this.edges[a.id]||{},e=this.edges[c.id]=this.edges[c.id]||{};d[c.id]=e[a.id]=new k.Adjacence(a,c,b,this.Edge,this.Label);return d[c.id]}return this.edges[a.id][c.id]},removeNode:function(a){if(this.hasNode(a)){delete this.nodes[a];var c=this.edges[a],b;for(b in c)delete this.edges[b][a];delete this.edges[a]}},removeAdjacence:function(a,c){delete this.edges[a][c];delete this.edges[c][a]},hasNode:function(a){return a in this.nodes},empty:function(){this.nodes=
{};this.edges={}}});var k=$jit.Graph,y;(function(){var a=function(a,c,b,h,g){var j,b=b||"current";if(b=="current")j=this.data;else if(b=="start")j=this.startData;else if(b=="end")j=this.endData;a="$"+(a?a+"-":"")+c;if(h)return j[a];if(!this.Config.overridable)return g[c]||0;return a in j?j[a]:a in this.data?this.data[a]:g[c]||0},c=function(a,c,b,h){var h=h||"current",g;if(h=="current")g=this.data;else if(h=="start")g=this.startData;else if(h=="end")g=this.endData;g["$"+(a?a+"-":"")+c]=b},b=function(a,
c){var a="$"+(a?a+"-":""),b=this;g.each(c,function(c){c=a+c;delete b.data[c];delete b.endData[c];delete b.startData[c]})};y={getData:function(c,b,f){return a.call(this,"",c,b,f,this.Config)},setData:function(a,b,f){c.call(this,"",a,b,f)},setDataset:function(a,c){var a=g.splat(a),b;for(b in c)for(var h=0,n=g.splat(c[b]),j=a.length;h<j;h++)this.setData(b,n[h],a[h])},removeData:function(){b.call(this,"",Array.prototype.slice.call(arguments))},getCanvasStyle:function(c,b,f){return a.call(this,"canvas",
c,b,f,this.Config.CanvasStyles)},setCanvasStyle:function(a,b,f){c.call(this,"canvas",a,b,f)},setCanvasStyles:function(a,c){var a=g.splat(a),b;for(b in c)for(var h=0,n=g.splat(c[b]),j=a.length;h<j;h++)this.setCanvasStyle(b,n[h],a[h])},removeCanvasStyle:function(){b.call(this,"canvas",Array.prototype.slice.call(arguments))},getLabelData:function(c,b,f){return a.call(this,"label",c,b,f,this.Label)},setLabelData:function(a,b,f){c.call(this,"label",a,b,f)},setLabelDataset:function(a,c){var a=g.splat(a),
b;for(b in c)for(var h=0,n=g.splat(c[b]),j=a.length;h<j;h++)this.setLabelData(b,n[h],a[h])},removeLabelData:function(){b.call(this,"label",Array.prototype.slice.call(arguments))}}})();k.Node=new i({initialize:function(a,c,b,d,e){c={id:"",name:"",data:{},startData:{},endData:{},adjacencies:{},selected:!1,drawn:!1,exist:!1,angleSpan:{begin:0,end:0},pos:c&&new o(0,0)||new r(0,0),startPos:c&&new o(0,0)||new r(0,0),endPos:c&&new o(0,0)||new r(0,0)};g.extend(this,g.extend(c,a));this.Config=this.Node=b;
this.Edge=d;this.Label=e},adjacentTo:function(a){return a.id in this.adjacencies},getAdjacency:function(a){return this.adjacencies[a]},getPos:function(a){a=a||"current";if(a=="current")return this.pos;else if(a=="end")return this.endPos;else if(a=="start")return this.startPos},setPos:function(a,c){var c=c||"current",b;if(c=="current")b=this.pos;else if(c=="end")b=this.endPos;else if(c=="start")b=this.startPos;b.set(a)}});k.Node.implement(y);k.Adjacence=new i({initialize:function(a,c,b,d,e){this.nodeFrom=
a;this.nodeTo=c;this.data=b||{};this.startData={};this.endData={};this.Config=this.Edge=d;this.Label=e}});k.Adjacence.implement(y);k.Util={filter:function(a){if(!a||g.type(a)!="string")return function(){return!0};var c=a.split(" ");return function(a){for(var d=0;d<c.length;d++)if(a[c[d]])return!1;return!0}},getNode:function(a,c){return a.nodes[c]},eachNode:function(a,c,b){var b=this.filter(b),d;for(d in a.nodes)b(a.nodes[d])&&c(a.nodes[d])},eachAdjacency:function(a,c,b){var d=a.adjacencies,b=this.filter(b),
e;for(e in d){var f=d[e];if(b(f)){if(f.nodeFrom!=a){var h=f.nodeFrom;f.nodeFrom=f.nodeTo;f.nodeTo=h}c(f,e)}}},computeLevels:function(a,c,b,d){var b=b||0,e=this.filter(d);this.eachNode(a,function(a){a._flag=!1;a._depth=-1},d);a=a.getNode(c);a._depth=b;for(var f=[a];f.length!=0;){var h=f.pop();h._flag=!0;this.eachAdjacency(h,function(a){a=a.nodeTo;if(a._flag==!1&&e(a)){if(a._depth<0)a._depth=h._depth+1+b;f.unshift(a)}},d)}},eachBFS:function(a,c,b,d){var e=this.filter(d);this.clean(a);for(var f=[a.getNode(c)];f.length!=
0;)a=f.pop(),a._flag=!0,b(a,a._depth),this.eachAdjacency(a,function(a){a=a.nodeTo;if(a._flag==!1&&e(a))a._flag=!0,f.unshift(a)},d)},eachLevel:function(a,c,b,d,e){var f=a._depth,h=this.filter(e),g=this,b=b===!1?Number.MAX_VALUE-f:b;(function v(a,c,b){var e=a._depth;e>=c&&e<=b&&h(a)&&d(a,e);e<b&&g.eachAdjacency(a,function(a){a=a.nodeTo;a._depth>e&&v(a,c,b)})})(a,c+f,b+f)},eachSubgraph:function(a,c,b){this.eachLevel(a,0,!1,c,b)},eachSubnode:function(a,c,b){this.eachLevel(a,1,1,c,b)},anySubnode:function(a,
c,b){var d=!1,c=c||g.lambda(!0),e=g.type(c)=="string"?function(a){return a[c]}:c;this.eachSubnode(a,function(a){e(a)&&(d=!0)},b);return d},getSubnodes:function(a,c,b){var d=[],c=c||0,e;g.type(c)=="array"?(e=c[0],c=c[1]):(e=c,c=Number.MAX_VALUE-a._depth);this.eachLevel(a,e,c,function(a){d.push(a)},b);return d},getParents:function(a){var c=[];this.eachAdjacency(a,function(b){b=b.nodeTo;b._depth<a._depth&&c.push(b)});return c},isDescendantOf:function(a,c){if(a.id==c)return!0;for(var b=this.getParents(a),
d=!1,e=0;!d&&e<b.length;e++)d=d||this.isDescendantOf(b[e],c);return d},clean:function(a){this.eachNode(a,function(a){a._flag=!1})},getClosestNodeToOrigin:function(a,c,b){return this.getClosestNodeToPos(a,r.KER,c,b)},getClosestNodeToPos:function(a,c,b,d){var e=null,b=b||"current",c=c&&c.getc(!0)||o.KER,f=function(a,c){var b=a.x-c.x,d=a.y-c.y;return b*b+d*d};this.eachNode(a,function(a){e=e==null||f(a.getPos(b).getc(!0),c)<f(e.getPos(b).getc(!0),c)?a:e},d);return e}};g.each(["getNode","eachNode","computeLevels",
"eachBFS","clean","getClosestNodeToPos","getClosestNodeToOrigin"],function(a){k.prototype[a]=function(){return k.Util[a].apply(k.Util,[this].concat(Array.prototype.slice.call(arguments)))}});g.each(["eachAdjacency","eachLevel","eachSubgraph","eachSubnode","anySubnode","getSubnodes","getParents","isDescendantOf"],function(a){k.Node.prototype[a]=function(){return k.Util[a].apply(k.Util,[this].concat(Array.prototype.slice.call(arguments)))}});k.Op={options:{type:"nothing",duration:2E3,hideLabels:!0,
fps:30},initialize:function(a){this.viz=a},removeNode:function(a,c){var b=this.viz,d=g.merge(this.options,b.controller,c),e=g.splat(a),f,h,n;switch(d.type){case "nothing":for(f=0;f<e.length;f++)b.graph.removeNode(e[f]);break;case "replot":this.removeNode(e,{type:"nothing"});b.labels.clearLabels();b.refresh(!0);break;case "fade:seq":case "fade":h=this;for(f=0;f<e.length;f++)n=b.graph.getNode(e[f]),n.setData("alpha",0,"end");b.fx.animate(g.merge(d,{modes:["node-property:alpha"],onComplete:function(){h.removeNode(e,
{type:"nothing"});b.labels.clearLabels();b.reposition();b.fx.animate(g.merge(d,{modes:["linear"]}))}}));break;case "fade:con":h=this;for(f=0;f<e.length;f++)n=b.graph.getNode(e[f]),n.setData("alpha",0,"end"),n.ignore=!0;b.reposition();b.fx.animate(g.merge(d,{modes:["node-property:alpha","linear"],onComplete:function(){h.removeNode(e,{type:"nothing"})}}));break;case "iter":h=this;b.fx.sequence({condition:function(){return e.length!=0},step:function(){h.removeNode(e.shift(),{type:"nothing"});b.labels.clearLabels()},
onComplete:function(){d.onComplete()},duration:Math.ceil(d.duration/e.length)});break;default:this.doError()}},removeEdge:function(a,c){var b=this.viz,d=g.merge(this.options,b.controller,c),e=g.type(a[0])=="string"?[a]:a,f,h,n;switch(d.type){case "nothing":for(f=0;f<e.length;f++)b.graph.removeAdjacence(e[f][0],e[f][1]);break;case "replot":this.removeEdge(e,{type:"nothing"});b.refresh(!0);break;case "fade:seq":case "fade":h=this;for(f=0;f<e.length;f++)(n=b.graph.getAdjacence(e[f][0],e[f][1]))&&n.setData("alpha",
0,"end");b.fx.animate(g.merge(d,{modes:["edge-property:alpha"],onComplete:function(){h.removeEdge(e,{type:"nothing"});b.reposition();b.fx.animate(g.merge(d,{modes:["linear"]}))}}));break;case "fade:con":h=this;for(f=0;f<e.length;f++)if(n=b.graph.getAdjacence(e[f][0],e[f][1]))n.setData("alpha",0,"end"),n.ignore=!0;b.reposition();b.fx.animate(g.merge(d,{modes:["edge-property:alpha","linear"],onComplete:function(){h.removeEdge(e,{type:"nothing"})}}));break;case "iter":h=this;b.fx.sequence({condition:function(){return e.length!=
0},step:function(){h.removeEdge(e.shift(),{type:"nothing"});b.labels.clearLabels()},onComplete:function(){d.onComplete()},duration:Math.ceil(d.duration/e.length)});break;default:this.doError()}},sum:function(a,c){var b=this.viz,d=g.merge(this.options,b.controller,c),e=b.root,f;b.root=c.id||b.root;switch(d.type){case "nothing":f=b.construct(a);f.eachNode(function(a){a.eachAdjacency(function(a){b.graph.addAdjacence(a.nodeFrom,a.nodeTo,a.data)})});break;case "replot":b.refresh(!0);this.sum(a,{type:"nothing"});
b.refresh(!0);break;case "fade:seq":case "fade":case "fade:con":that=this;f=b.construct(a);var h=!this.preprocessSum(f)?["node-property:alpha"]:["node-property:alpha","edge-property:alpha"];b.reposition();d.type!="fade:con"?b.fx.animate(g.merge(d,{modes:["linear"],onComplete:function(){b.fx.animate(g.merge(d,{modes:h,onComplete:function(){d.onComplete()}}))}})):(b.graph.eachNode(function(a){a.id!=e&&a.pos.getp().equals(r.KER)&&(a.pos.set(a.endPos),a.startPos.set(a.endPos))}),b.fx.animate(g.merge(d,
{modes:["linear"].concat(h)})));break;default:this.doError()}},morph:function(a,c,b){var d=this.viz,e=g.merge(this.options,d.controller,c),f=d.root,h;d.root=c.id||d.root;switch(e.type){case "nothing":h=d.construct(a);h.eachNode(function(a){var c=d.graph.hasNode(a.id);a.eachAdjacency(function(a){var c=!!d.graph.getAdjacence(a.nodeFrom.id,a.nodeTo.id);d.graph.addAdjacence(a.nodeFrom,a.nodeTo,a.data);if(c){var c=d.graph.getAdjacence(a.nodeFrom.id,a.nodeTo.id),b;for(b in a.data||{})c.data[b]=a.data[b]}});
if(c){var c=d.graph.getNode(a.id),b;for(b in a.data||{})c.data[b]=a.data[b]}});d.graph.eachNode(function(a){a.eachAdjacency(function(a){h.getAdjacence(a.nodeFrom.id,a.nodeTo.id)||d.graph.removeAdjacence(a.nodeFrom.id,a.nodeTo.id)});h.hasNode(a.id)||d.graph.removeNode(a.id)});break;case "replot":d.labels.clearLabels(!0);this.morph(a,{type:"nothing"});d.refresh(!0);d.refresh(!0);break;case "fade:seq":case "fade":case "fade:con":that=this;h=d.construct(a);var n=b&&"node-property"in b&&g.map(g.splat(b["node-property"]),
function(a){return"$"+a});d.graph.eachNode(function(a){var c=h.getNode(a.id);if(c){var c=c.data,b;for(b in c)n&&g.indexOf(n,b)>-1?a.endData[b]=c[b]:a.data[b]=c[b]}else a.setData("alpha",1),a.setData("alpha",1,"start"),a.setData("alpha",0,"end"),a.ignore=!0});d.graph.eachNode(function(a){a.ignore||a.eachAdjacency(function(a){if(!a.nodeFrom.ignore&&!a.nodeTo.ignore){var c=h.getNode(a.nodeFrom.id),a=h.getNode(a.nodeTo.id);c.adjacentTo(a)||(a=d.graph.getAdjacence(c.id,a.id),j=!0,a.setData("alpha",1),
a.setData("alpha",1,"start"),a.setData("alpha",0,"end"))}})});var j=this.preprocessSum(h),a=!j?["node-property:alpha"]:["node-property:alpha","edge-property:alpha"];a[0]+=b&&"node-property"in b?":"+g.splat(b["node-property"]).join(":"):"";a[1]=(a[1]||"edge-property:alpha")+(b&&"edge-property"in b?":"+g.splat(b["edge-property"]).join(":"):"");b&&"label-property"in b&&a.push("label-property:"+g.splat(b["label-property"]).join(":"));d.reposition();d.graph.eachNode(function(a){a.id!=f&&a.pos.getp().equals(r.KER)&&
(a.pos.set(a.endPos),a.startPos.set(a.endPos))});d.fx.animate(g.merge(e,{modes:["polar"].concat(a),onComplete:function(){d.graph.eachNode(function(a){a.ignore&&d.graph.removeNode(a.id)});d.graph.eachNode(function(a){a.eachAdjacency(function(a){a.ignore&&d.graph.removeAdjacence(a.nodeFrom.id,a.nodeTo.id)})});e.onComplete()}}))}},contract:function(a,c){var b=this.viz;if(!a.collapsed&&a.anySubnode(g.lambda(!0)))c=g.merge(this.options,b.config,c||{},{modes:["node-property:alpha:span","linear"]}),a.collapsed=
!0,function e(a){a.eachSubnode(function(a){a.ignore=!0;a.setData("alpha",0,c.type=="animate"?"end":"current");e(a)})}(a),c.type=="animate"?(b.compute("end"),b.rotated&&b.rotate(b.rotated,"none",{property:"end"}),function f(c){c.eachSubnode(function(c){c.setPos(a.getPos("end"),"end");f(c)})}(a),b.fx.animate(c)):c.type=="replot"&&b.refresh()},expand:function(a,c){if("collapsed"in a){var b=this.viz,c=g.merge(this.options,b.config,c||{},{modes:["node-property:alpha:span","linear"]});delete a.collapsed;
(function e(a){a.eachSubnode(function(a){delete a.ignore;a.setData("alpha",1,c.type=="animate"?"end":"current");e(a)})})(a);c.type=="animate"?(b.compute("end"),b.rotated&&b.rotate(b.rotated,"none",{property:"end"}),b.fx.animate(c)):c.type=="replot"&&b.refresh()}},preprocessSum:function(a){var c=this.viz;a.eachNode(function(a){c.graph.hasNode(a.id)||(c.graph.addNode(a),a=c.graph.getNode(a.id),a.setData("alpha",0),a.setData("alpha",0,"start"),a.setData("alpha",1,"end"))});var b=!1;a.eachNode(function(a){a.eachAdjacency(function(a){var d=
c.graph.getNode(a.nodeFrom.id),h=c.graph.getNode(a.nodeTo.id);d.adjacentTo(h)||(a=c.graph.addAdjacence(d,h,a.data),d.startAlpha==d.endAlpha&&h.startAlpha==h.endAlpha&&(b=!0,a.setData("alpha",0),a.setData("alpha",0,"start"),a.setData("alpha",1,"end")))})});return b}};var A={none:{render:g.empty,contains:g.lambda(!1)},circle:{render:function(a,c,b,d){d=d.getCtx();d.beginPath();d.arc(c.x,c.y,b,0,Math.PI*2,!0);d.closePath();d[a]()},contains:function(a,c,b){var d=a.x-c.x,a=a.y-c.y;return d*d+a*a<=b*b}},
ellipse:{render:function(a,c,b,d,e){e=e.getCtx();d/=2;b/=2;e.save();e.scale(b/d,d/b);e.beginPath();e.arc(c.x*(d/b),c.y*(b/d),d,0,Math.PI*2,!0);e.closePath();e[a]();e.restore()},contains:function(a,c,b,d){b/=2;d/=2;b=(b+d)/2;d=a.x-c.x;a=a.y-c.y;return d*d+a*a<=b*b}},square:{render:function(a,c,b,d){d.getCtx()[a+"Rect"](c.x-b,c.y-b,2*b,2*b)},contains:function(a,c,b){return Math.abs(c.x-a.x)<=b&&Math.abs(c.y-a.y)<=b}},rectangle:{render:function(a,c,b,d,e){e.getCtx()[a+"Rect"](c.x-b/2,c.y-d/2,b,d)},contains:function(a,
c,b,d){return Math.abs(c.x-a.x)<=b/2&&Math.abs(c.y-a.y)<=d/2}},triangle:{render:function(a,c,b,d){var d=d.getCtx(),e=c.x,f=c.y-b,h=e-b,c=c.y+b,b=e+b;d.beginPath();d.moveTo(e,f);d.lineTo(h,c);d.lineTo(b,c);d.closePath();d[a]()},contains:function(a,c,b){return A.circle.contains(a,c,b)}},star:{render:function(a,c,b,d){var d=d.getCtx(),e=Math.PI/5;d.save();d.translate(c.x,c.y);d.beginPath();d.moveTo(b,0);for(c=0;c<9;c++)d.rotate(e),c%2==0?d.lineTo(b/0.525731*0.200811,0):d.lineTo(b,0);d.closePath();d[a]();
d.restore()},contains:function(a,c,b){return A.circle.contains(a,c,b)}}},B={line:{render:function(a,c,b){b=b.getCtx();b.beginPath();b.moveTo(a.x,a.y);b.lineTo(c.x,c.y);b.stroke()},contains:function(a,c,b,d){var e=Math.min,f=Math.max,h=e(a.x,c.x),g=f(a.x,c.x),e=e(a.y,c.y),f=f(a.y,c.y);if(b.x>=h&&b.x<=g&&b.y>=e&&b.y<=f){if(Math.abs(c.x-a.x)<=d)return!0;return Math.abs((c.y-a.y)/(c.x-a.x)*(b.x-a.x)+a.y-b.y)<=d}return!1}},arrow:{render:function(a,c,b,d,e){e=e.getCtx();d&&(d=a,a=c,c=d);d=new o(c.x-a.x,
c.y-a.y);d.$scale(b/d.norm());var b=new o(c.x-d.x,c.y-d.y),f=new o(-d.y/2,d.x/2),d=b.add(f),b=b.$add(f.$scale(-1));e.beginPath();e.moveTo(a.x,a.y);e.lineTo(c.x,c.y);e.stroke();e.beginPath();e.moveTo(d.x,d.y);e.lineTo(b.x,b.y);e.lineTo(c.x,c.y);e.closePath();e.fill()},contains:function(a,c,b,d){return B.line.contains(a,c,b,d)}},hyperline:{render:function(a,c,b,d){function e(a,c){return a<c?a+Math.PI>c?!1:!0:c+Math.PI>a?!0:!1}var d=d.getCtx(),f=function(a,c){var b=a.x*c.y-a.y*c.x,d=a.squaredNorm(),
e=c.squaredNorm();if(b==0)return{x:0,y:0,ratio:-1};var f=(a.y*e-c.y*d+a.y-c.y)/b,b=(c.x*d-a.x*e+c.x-a.x)/b,d=(f*f+b*b)/4-1;if(d<0)return{x:0,y:0,ratio:-1};d=Math.sqrt(d);return{x:-f/2,y:-b/2,ratio:d>1E3?-1:d,a:f,b:b}}(a,c);f.a>1E3||f.b>1E3||f.ratio<0?(d.beginPath(),d.moveTo(a.x*b,a.y*b),d.lineTo(c.x*b,c.y*b)):(c=Math.atan2(c.y-f.y,c.x-f.x),a=Math.atan2(a.y-f.y,a.x-f.x),e=e(c,a),d.beginPath(),d.arc(f.x*b,f.y*b,f.ratio*b,c,a,e));d.stroke()},contains:g.lambda(!1)}};k.Plot={initialize:function(a,c){this.viz=
a;this.config=a.config;this.node=a.config.Node;this.edge=a.config.Edge;this.animation=new z;this.nodeTypes=new c.Plot.NodeTypes;this.edgeTypes=new c.Plot.EdgeTypes;this.labels=a.labels},nodeHelper:A,edgeHelper:B,Interpolator:{map:{border:"color",color:"color",width:"number",height:"number",dim:"number",alpha:"number",lineWidth:"number",angularWidth:"number",span:"number",valueArray:"array-number",dimArray:"array-number"},canvas:{globalAlpha:"number",fillStyle:"color",strokeStyle:"color",lineWidth:"number",
shadowBlur:"number",shadowColor:"color",shadowOffsetX:"number",shadowOffsetY:"number",miterLimit:"number"},label:{size:"number",color:"color"},compute:function(a,c,b){return a+(c-a)*b},moebius:function(a,c,b,d){c=d.scale(-b);if(c.norm()<1){var b=c.x,d=c.y,e=a.startPos.getc().moebiusTransformation(c);a.pos.setc(e.x,e.y);c.x=b;c.y=d}},linear:function(a,c,b){var c=a.startPos.getc(!0),d=a.endPos.getc(!0);a.pos.setc(this.compute(c.x,d.x,b),this.compute(c.y,d.y,b))},polar:function(a,c,b){c=a.startPos.getp(!0);
b=a.endPos.getp().interpolate(c,b);a.pos.setp(b.theta,b.rho)},number:function(a,c,b,d,e){var f=a[d](c,"start"),d=a[d](c,"end");a[e](c,this.compute(f,d,b))},color:function(a,c,b,d,e){var f=g.hexToRgb(a[d](c,"start")),d=g.hexToRgb(a[d](c,"end")),h=this.compute,b=g.rgbToHex([parseInt(h(f[0],d[0],b)),parseInt(h(f[1],d[1],b)),parseInt(h(f[2],d[2],b))]);a[e](c,b)},"array-number":function(a,c,b,d,e){for(var f=a[d](c,"start"),d=a[d](c,"end"),h=[],g=0,j=f.length;g<j;g++){var v=f[g],m=d[g];if(v.length){for(var i=
0,k=v.length,l=[];i<k;i++)l.push(this.compute(v[i],m[i],b));h.push(l)}else h.push(this.compute(v,m,b))}a[e](c,h)},node:function(a,c,b,d,e,f){d=this[d];if(c)for(var h=c.length,g=0;g<h;g++){var j=c[g];this[d[j]](a,j,b,e,f)}else for(j in d)this[d[j]](a,j,b,e,f)},edge:function(a,c,b,d,e,f){var a=a.adjacencies,h;for(h in a)this.node(a[h],c,b,d,e,f)},"node-property":function(a,c,b){this.node(a,c,b,"map","getData","setData")},"edge-property":function(a,c,b){this.edge(a,c,b,"map","getData","setData")},"label-property":function(a,
c,b){this.node(a,c,b,"label","getLabelData","setLabelData")},"node-style":function(a,c,b){this.node(a,c,b,"canvas","getCanvasStyle","setCanvasStyle")},"edge-style":function(a,c,b){this.edge(a,c,b,"canvas","getCanvasStyle","setCanvasStyle")}},sequence:function(a){var c=this,a=g.merge({condition:g.lambda(!1),step:g.empty,onComplete:g.empty,duration:200},a||{}),b=setInterval(function(){a.condition()?a.step():(clearInterval(b),a.onComplete());c.viz.refresh(!0)},a.duration)},prepare:function(a){var c=
this.viz.graph,b={"node-property":{getter:"getData",setter:"setData"},"edge-property":{getter:"getData",setter:"setData"},"node-style":{getter:"getCanvasStyle",setter:"setCanvasStyle"},"edge-style":{getter:"getCanvasStyle",setter:"setCanvasStyle"}},d={};if(g.type(a)=="array")for(var e=0,f=a.length;e<f;e++){var h=a[e].split(":");d[h.shift()]=h}else for(e in a)e=="position"?d[a.position]=[]:d[e]=g.splat(a[e]);c.eachNode(function(a){a.startPos.set(a.pos);g.each(["node-property","node-style"],function(c){if(c in
d)for(var e=d[c],f=0,h=e.length;f<h;f++)a[b[c].setter](e[f],a[b[c].getter](e[f]),"start")});g.each(["edge-property","edge-style"],function(c){if(c in d){var e=d[c];a.eachAdjacency(function(a){for(var d=0,f=e.length;d<f;d++)a[b[c].setter](e[d],a[b[c].getter](e[d]),"start")})}})});return d},animate:function(a,c){var a=g.merge(this.viz.config,a||{}),b=this,d=this.viz.graph,e=this.Interpolator,f=a.type==="nodefx"?this.nodeFxAnimation:this.animation,h=this.prepare(a.modes);a.hideLabels&&this.labels.hideLabels(!0);
f.setOptions(g.merge(a,{$animating:!1,compute:function(f){d.eachNode(function(a){for(var b in h)e[b](a,h[b],f,c)});b.plot(a,this.$animating,f);this.$animating=!0},complete:function(){a.hideLabels&&b.labels.hideLabels(!1);b.plot(a);a.onComplete();a.onAfterCompute()}})).start()},nodeFx:function(a){var c=this.viz,b=c.graph,d=this.nodeFxAnimation,e=g.merge(this.viz.config,{elements:{id:!1,properties:{}},reposition:!1}),a=g.merge(e,a||{},{onBeforeCompute:g.empty,onAfterCompute:g.empty});d.stopTimer();
var f=a.elements.properties;a.elements.id?(d=g.splat(a.elements.id),g.each(d,function(a){if(a=b.getNode(a))for(var c in f)a.setData(c,f[c],"end")})):b.eachNode(function(a){for(var c in f)a.setData(c,f[c],"end")});var d=[],h;for(h in f)d.push(h);h=["node-property:"+d.join(":")];a.reposition&&(h.push("linear"),c.compute("end"));this.animate(g.merge(a,{modes:h,type:"nodefx"}))},plot:function(a,c){var b=this.viz,d=b.graph,e=b.canvas,b=b.root,f=this,h=e.getCtx(),g=Math.min,a=a||this.viz.controller;a.clearCanvas&&
e.clear();if(b=d.getNode(b)){var j=!!b.visited;d.eachNode(function(b){var d=b.getData("alpha");b.eachAdjacency(function(i){var k=i.nodeTo;if(!!k.visited===j&&b.drawn&&k.drawn)!c&&a.onBeforePlotLine(i),h.save(),h.globalAlpha=g(d,k.getData("alpha"),i.getData("alpha")),f.plotLine(i,e,c),h.restore(),!c&&a.onAfterPlotLine(i)});h.save();b.drawn&&(!c&&a.onBeforePlotNode(b),f.plotNode(b,e,c),!c&&a.onAfterPlotNode(b));!f.labelsHidden&&a.withLabels&&(b.drawn&&d>=0.95?f.labels.plotLabel(e,b,a):f.labels.hideLabel(b,
!1));h.restore();b.visited=!j})}},plotTree:function(a,c,b){var d=this,e=this.viz.canvas,f=e.getCtx(),h=a.getData("alpha");a.eachSubnode(function(g){if(c.plotSubtree(a,g)&&g.exist&&g.drawn){var j=a.getAdjacency(g.id);!b&&c.onBeforePlotLine(j);f.globalAlpha=Math.min(h,g.getData("alpha"));d.plotLine(j,e,b);!b&&c.onAfterPlotLine(j);d.plotTree(g,c,b)}});a.drawn?(!b&&c.onBeforePlotNode(a),this.plotNode(a,e,b),!b&&c.onAfterPlotNode(a),!c.hideLabels&&c.withLabels&&h>=0.95?this.labels.plotLabel(e,a,c):this.labels.hideLabel(a,
!1)):this.labels.hideLabel(a,!0)},plotNode:function(a,c,b){var d=a.getData("type"),e=this.node.CanvasStyles;if(d!="none"){var f=a.getData("lineWidth"),h=a.getData("color"),g=a.getData("alpha"),j=c.getCtx();j.lineWidth=f;j.fillStyle=j.strokeStyle=h;j.globalAlpha=g;for(var i in e)j[i]=a.getCanvasStyle(i);this.nodeTypes[d].render.call(this,a,c,b)}},plotLine:function(a,c,b){var d=a.getData("type"),e=this.edge.CanvasStyles;if(d!="none"){var f=a.getData("lineWidth"),h=a.getData("color"),g=c.getCtx();g.lineWidth=
f;g.fillStyle=g.strokeStyle=h;for(var j in e)g[j]=a.getCanvasStyle(j);this.edgeTypes[d].render.call(this,a,c,b)}}};k.Label={};k.Label.Native=new i({plotLabel:function(a,c,b){var d=a.getCtx();c.pos.getc(!0);d.font=c.getLabelData("style")+" "+c.getLabelData("size")+"px "+c.getLabelData("family");d.textAlign=c.getLabelData("textAlign");d.fillStyle=d.strokeStyle=c.getLabelData("color");d.textBaseline=c.getLabelData("textBaseline");this.renderLabel(a,c,b)},renderLabel:function(a,c){var b=a.getCtx(),d=
c.pos.getc(!0);b.fillText(c.name,d.x,d.y+c.getData("height")/2)},hideLabel:g.empty,hideLabels:g.empty});k.Label.DOM=new i({labelsHidden:!1,labelContainer:!1,labels:{},getLabelContainer:function(){return this.labelContainer?this.labelContainer:this.labelContainer=document.getElementById(this.viz.config.labelContainer)},getLabel:function(a){return a in this.labels&&this.labels[a]!=null?this.labels[a]:this.labels[a]=document.getElementById(a)},hideLabels:function(a){this.getLabelContainer().style.display=
a?"none":"";this.labelsHidden=a},clearLabels:function(a){for(var c in this.labels)if(a||!this.viz.graph.hasNode(c))this.disposeLabel(c),delete this.labels[c]},disposeLabel:function(a){(a=this.getLabel(a))&&a.parentNode&&a.parentNode.removeChild(a)},hideLabel:function(a,c){var a=g.splat(a),b=c?"":"none",d=this;g.each(a,function(a){if(a=d.getLabel(a.id))a.style.display=b})},fitsInCanvas:function(a,c){var b=c.getSize();if(a.x>=b.width||a.x<0||a.y>=b.height||a.y<0)return!1;return!0}});k.Label.HTML=new i({Implements:k.Label.DOM,
plotLabel:function(a,c,b){var a=c.id,d=this.getLabel(a);if(!d&&!(d=document.getElementById(a))){var d=document.createElement("div"),e=this.getLabelContainer();d.id=a;d.className="node";d.style.position="absolute";b.onCreateLabel(d,c);e.appendChild(d);this.labels[c.id]=d}this.placeLabel(d,c,b)}});k.Label.SVG=new i({Implements:k.Label.DOM,plotLabel:function(a,c,b){var a=c.id,d=this.getLabel(a);if(!d&&!(d=document.getElementById(a))){var d=document.createElementNS("http://www.w3.org/2000/svg","svg:text"),
e=document.createElementNS("http://www.w3.org/2000/svg","svg:tspan");d.appendChild(e);e=this.getLabelContainer();d.setAttribute("id",a);d.setAttribute("class","node");e.appendChild(d);b.onCreateLabel(d,c);this.labels[c.id]=d}this.placeLabel(d,c,b)}});var t={construct:function(a){var c=g.type(a)=="array",b=new k(this.graphOptions,this.config.Node,this.config.Edge,this.config.Label);c?function(a,c){for(var b=function(b){for(var f=0,h=c.length;f<h;f++)if(c[f].id==b)return c[f];return a.addNode({id:b,
name:b})},h=0,n=c.length;h<n;h++){a.addNode(c[h]);var j=c[h].adjacencies;if(j)for(var i=0,m=j.length;i<m;i++){var k=j[i],l={};if(typeof j[i]!="string")l=g.merge(k.data,{}),k=k.nodeTo;a.addAdjacence(c[h],b(k),l)}}}(b,a):function(a,c){a.addNode(c);if(c.children)for(var b=0,h=c.children;b<h.length;b++)a.addAdjacence(c,h[b]),arguments.callee(a,h[b])}(b,a);return b},loadJSON:function(a,c){this.json=a;this.labels&&this.labels.clearLabels&&this.labels.clearLabels(!0);this.graph=this.construct(a);this.root=
g.type(a)!="array"?a.id:a[c?c:0].id},toJSON:function(a){if((a||"tree")=="tree")var c={},c=function e(a){var c={};c.id=a.id;c.name=a.name;c.data=a.data;var b=[];a.eachSubnode(function(a){b.push(e(a))});c.children=b;return c}(this.graph.getNode(this.root));else{var c=[],b=!!this.graph.getNode(this.root).visited;this.graph.eachNode(function(a){var f={};f.id=a.id;f.name=a.name;f.data=a.data;var h=[];a.eachAdjacency(function(a){var c=a.nodeTo;if(!!c.visited===b){var e={};e.nodeTo=c.id;e.data=a.data;h.push(e)}});
f.adjacencies=h;c.push(f);a.visited=!b})}return c}},p=$jit.Layouts={},D={label:null,compute:function(a,c,b){this.initializeLabel(b);var d=this.label,e=d.style;a.eachNode(function(a){var c=a.getData("autoWidth"),b=a.getData("autoHeight");if(c||b){delete a.data.$width;delete a.data.$height;delete a.data.$dim;var j=a.getData("width"),i=a.getData("height");e.width=c?"auto":j+"px";e.height=b?"auto":i+"px";d.innerHTML=a.name;c=d.offsetWidth;b=d.offsetHeight;j=a.getData("type");g.indexOf(["circle","square",
"triangle","star"],j)===-1?(a.setData("width",c),a.setData("height",b)):(c=c>b?c:b,a.setData("width",c),a.setData("height",c),a.setData("dim",c))}})},initializeLabel:function(a){if(!this.label)this.label=document.createElement("div"),document.body.appendChild(this.label);this.setLabelStyles(a)},setLabelStyles:function(){g.extend(this.label.style,{visibility:"hidden",position:"absolute",width:"auto",height:"auto"});this.label.className="jit-autoadjust-label"}};p.Radial=new i({compute:function(a){a=
g.splat(a||["current","start","end"]);D.compute(this.graph,a,this.config);this.graph.computeLevels(this.root,0,"ignore");var c=this.createLevelDistanceFunc();this.computeAngularWidths(a);this.computePositions(a,c)},computePositions:function(a,c){for(var b=this.graph,d=b.getNode(this.root),e=this.parent,f=0,h=a.length;f<h;f++){var g=a[f];d.setPos(new r(0,0),g);d.setData("span",Math.PI*2,g)}d.angleSpan={begin:0,end:2*Math.PI};b.eachBFS(this.root,function(b){var d=b.angleSpan.end-b.angleSpan.begin,f=
b.angleSpan.begin,g=c(b),h=0,n=[],i={};b.eachSubnode(function(c){h+=c._treeAngularWidth;for(var b=0,d=a.length;b<d;b++){var e=a[b],f=c.getData("dim",e);i[e]=e in i?f>i[e]?f:i[e]:f}n.push(c)},"ignore");e&&e.id==b.id&&n.length>0&&n[0].dist&&n.sort(function(a,c){return(a.dist>=c.dist)-(a.dist<=c.dist)});for(var b=0,k=n.length;b<k;b++){var l=n[b];if(!l._flag){for(var o=l._treeAngularWidth/h*d,p=f+o/2,q=0,t=a.length;q<t;q++){var s=a[q];l.setPos(new r(p,g),s);l.setData("span",o,s);l.setData("dim-quotient",
l.getData("dim",s)/i[s],s)}l.angleSpan={begin:f,end:f+o};f+=o}}},"ignore")},setAngularWidthForNodes:function(a){this.graph.eachBFS(this.root,function(c,b){var d=c.getData("angularWidth",a[0])||5;c._angularWidth=d/b},"ignore")},setSubtreesAngularWidth:function(){var a=this;this.graph.eachNode(function(c){a.setSubtreeAngularWidth(c)},"ignore")},setSubtreeAngularWidth:function(a){var c=this,b=a._angularWidth,d=0;a.eachSubnode(function(a){c.setSubtreeAngularWidth(a);d+=a._treeAngularWidth},"ignore");
a._treeAngularWidth=Math.max(b,d)},computeAngularWidths:function(a){this.setAngularWidthForNodes(a);this.setSubtreesAngularWidth()}});o.prototype.moebiusTransformation=function(a){var c=this.add(a),a=a.$conjugate().$prod(this);a.x++;return c.$div(a)};k.Util.moebiusTransformation=function(a,c,b,d,e){this.eachNode(a,function(a){for(var e=0;e<b.length;e++){var g=c[e].scale(-1),j=d?d:b[e];a.getPos(b[e]).set(a.getPos(j).getc().moebiusTransformation(g))}},e)};$jit.Hypertree=new i({Implements:[t,s,p.Radial],
initialize:function(a){var c=$jit.Hypertree,a=this.controller=this.config=g.merge(q("Canvas","Node","Edge","Fx","Tips","NodeStyles","Events","Navigation","Controller","Label"),{radius:"auto",offset:0,Edge:{type:"hyperline"},duration:1500,fps:35},a);if(a.useCanvas)this.canvas=a.useCanvas,this.config.labelContainer=this.canvas.id+"-label";else{if(a.background)a.background=g.merge({type:"Circles"},a.background);this.canvas=new u(this,a);this.config.labelContainer=(typeof a.injectInto=="string"?a.injectInto:
a.injectInto.id)+"-label"}this.graphOptions={complex:!1,Node:{selected:!1,exist:!0,drawn:!0}};this.graph=new k(this.graphOptions,this.config.Node,this.config.Edge);this.labels=new c.Label[a.Label.type](this);this.fx=new c.Plot(this,c);this.op=new c.Op(this);this.root=this.json=null;this.busy=!1;this.initializeExtras()},createLevelDistanceFunc:function(){var a=this.getRadius(),c=0,b=Math.max,d=this.config;this.graph.eachNode(function(a){c=b(a._depth,c)},"ignore");c++;for(var e=function(c){return function(b){b.scale=
a;for(var b=b._depth+1,e=0,f=Math.pow;b;)e+=f(c,b--);return e-d.offset}},f=0.51;f<=1;f+=0.01)if((1-Math.pow(f,c))/(1-f)>=2)return e(f-0.01);return e(0.75)},getRadius:function(){var a=this.config.radius;if(a!=="auto")return a;a=this.canvas.getSize();return Math.min(a.width,a.height)/2},refresh:function(a){a?(this.reposition(),this.graph.eachNode(function(a){a.startPos.rho=a.pos.rho=a.endPos.rho;a.startPos.theta=a.pos.theta=a.endPos.theta})):this.compute();this.plot()},reposition:function(){this.compute("end");
var a=this.graph.getNode(this.root).pos.getc().scale(-1);k.Util.moebiusTransformation(this.graph,[a],["end"],"end","ignore");this.graph.eachNode(function(a){if(a.ignore)a.endPos.rho=a.pos.rho,a.endPos.theta=a.pos.theta})},plot:function(){this.fx.plot()},onClick:function(a,c){this.move(this.graph.getNode(a).pos.getc(!0),c)},move:function(a,c){var b=new o(a.x,a.y);if(this.busy===!1&&b.norm()<1){this.busy=!0;var d=this.graph.getClosestNodeToPos(b),e=this;this.graph.computeLevels(d.id,0);this.controller.onBeforeCompute(d);
c=g.merge({onComplete:g.empty},c||{});this.fx.animate(g.merge({modes:["moebius"],hideLabels:!0},c,{onComplete:function(){e.busy=!1;c.onComplete()}}),b)}}});$jit.Hypertree.$extend=!0;(function(a){a.Op=new i({Implements:k.Op});a.Plot=new i({Implements:k.Plot});a.Label={};a.Label.Native=new i({Implements:k.Label.Native,initialize:function(a){this.viz=a},renderLabel:function(a,b){var d=a.getCtx(),e=b.pos.getc(!0),f=this.viz.getRadius();d.fillText(b.name,e.x*f,e.y*f)}});a.Label.SVG=new i({Implements:k.Label.SVG,
initialize:function(a){this.viz=a},placeLabel:function(a,b,d){var e=b.pos.getc(!0),f=this.viz.canvas,g=f.translateOffsetX,n=f.translateOffsetY,j=f.scaleOffsetX,i=f.scaleOffsetY,f=f.getSize(),k=this.viz.getRadius(),e={x:Math.round(e.x*j*k+g+f.width/2),y:Math.round(e.y*i*k+n+f.height/2)};a.setAttribute("x",e.x);a.setAttribute("y",e.y);d.onPlaceLabel(a,b)}});a.Label.HTML=new i({Implements:k.Label.HTML,initialize:function(a){this.viz=a},placeLabel:function(a,b,d){var e=b.pos.getc(!0),f=this.viz.canvas,
g=f.translateOffsetX,n=f.translateOffsetY,j=f.scaleOffsetX,i=f.scaleOffsetY,k=f.getSize(),l=this.viz.getRadius(),e={x:Math.round(e.x*j*l+g+k.width/2),y:Math.round(e.y*i*l+n+k.height/2)},g=a.style;g.left=e.x+"px";g.top=e.y+"px";g.display=this.fitsInCanvas(e,f)?"":"none";d.onPlaceLabel(a,b)}});a.Plot.NodeTypes=new i({none:{render:g.empty,contains:g.lambda(!1)},circle:{render:function(a,b){var d=this.node,e=a.getData("dim"),f=a.pos.getc(),e=d.transform?e*(1-f.squaredNorm()):e;f.$scale(a.scale);e>0.2&&
this.nodeHelper.circle.render("fill",f,e,b)},contains:function(a,b){var d=a.getData("dim");return this.nodeHelper.circle.contains(a.pos.getc().$scale(a.scale),b,d)}},ellipse:{render:function(a,b){var d=a.pos.getc().$scale(a.scale),e=a.getData("width"),f=a.getData("height");this.nodeHelper.ellipse.render("fill",d,e,f,b)},contains:function(a,b){var d=a.getData("width"),e=a.getData("height");return this.nodeHelper.circle.contains(a.pos.getc().$scale(a.scale),b,d,e)}},square:{render:function(a,b){var d=
this.node,e=a.getData("dim"),f=a.pos.getc(),e=d.transform?e*(1-f.squaredNorm()):e;f.$scale(a.scale);e>0.2&&this.nodeHelper.square.render("fill",f,e,b)},contains:function(a,b){var d=a.getData("dim");return this.nodeHelper.square.contains(a.pos.getc().$scale(a.scale),b,d)}},rectangle:{render:function(a,b){var d=this.node,e=a.getData("width"),f=a.getData("height"),g=a.pos.getc(),e=d.transform?e*(1-g.squaredNorm()):e,f=d.transform?f*(1-g.squaredNorm()):f;g.$scale(a.scale);e>0.2&&f>0.2&&this.nodeHelper.rectangle.render("fill",
g,e,f,b)},contains:function(a,b){var d=a.getData("width"),e=a.getData("height");return this.nodeHelper.square.contains(a.pos.getc().$scale(a.scale),b,d,e)}},triangle:{render:function(a,b){var d=this.node,e=a.getData("dim"),f=a.pos.getc(),e=d.transform?e*(1-f.squaredNorm()):e;f.$scale(a.scale);e>0.2&&this.nodeHelper.triangle.render("fill",f,e,b)},contains:function(a,b){var d=a.getData("dim");return this.nodeHelper.triangle.contains(a.pos.getc().$scale(a.scale),b,d)}},star:{render:function(a,b){var d=
this.node,e=a.getData("dim"),f=a.pos.getc(),e=d.transform?e*(1-f.squaredNorm()):e;f.$scale(a.scale);e>0.2&&this.nodeHelper.star.render("fill",f,e,b)},contains:function(a,b){var d=a.getData("dim");return this.nodeHelper.star.contains(a.pos.getc().$scale(a.scale),b,d)}}});a.Plot.EdgeTypes=new i({none:g.empty,line:{render:function(a,b){var d=a.nodeFrom.pos.getc(!0),e=a.nodeTo.pos.getc(!0),f=a.nodeFrom.scale;this.edgeHelper.line.render({x:d.x*f,y:d.y*f},{x:e.x*f,y:e.y*f},b)},contains:function(a,b){var d=
a.nodeFrom.pos.getc(!0),e=a.nodeTo.pos.getc(!0),f=a.nodeFrom.scale;this.edgeHelper.line.contains({x:d.x*f,y:d.y*f},{x:e.x*f,y:e.y*f},b,this.edge.epsilon)}},arrow:{render:function(a,b){var d=a.nodeFrom.pos.getc(!0),e=a.nodeTo.pos.getc(!0),f=a.nodeFrom.scale,g=a.getData("dim"),n=a.data.$direction;this.edgeHelper.arrow.render({x:d.x*f,y:d.y*f},{x:e.x*f,y:e.y*f},g,n&&n.length>1&&n[0]!=a.nodeFrom.id,b)},contains:function(a,b){var d=a.nodeFrom.pos.getc(!0),e=a.nodeTo.pos.getc(!0),f=a.nodeFrom.scale;this.edgeHelper.arrow.contains({x:d.x*
f,y:d.y*f},{x:e.x*f,y:e.y*f},b,this.edge.epsilon)}},hyperline:{render:function(a,b){var d=a.nodeFrom.pos.getc(),e=a.nodeTo.pos.getc(),f=this.viz.getRadius();this.edgeHelper.hyperline.render(d,e,f,b)},contains:g.lambda(!1)}})})($jit.Hypertree);$jit.RGraph=new i({Implements:[t,s,p.Radial],initialize:function(a){var c=$jit.RGraph,a=this.controller=this.config=g.merge(q("Canvas","Node","Edge","Fx","Controller","Tips","NodeStyles","Events","Navigation","Label"),{interpolation:"linear",levelDistance:100},
a);if(a.useCanvas)this.canvas=a.useCanvas,this.config.labelContainer=this.canvas.id+"-label";else{if(a.background)a.background=g.merge({type:"Circles"},a.background);this.canvas=new u(this,a);this.config.labelContainer=(typeof a.injectInto=="string"?a.injectInto:a.injectInto.id)+"-label"}this.graphOptions={complex:!1,Node:{selected:!1,exist:!0,drawn:!0}};this.graph=new k(this.graphOptions,this.config.Node,this.config.Edge);this.labels=new c.Label[a.Label.type](this);this.fx=new c.Plot(this,c);this.op=
new c.Op(this);this.root=this.json=null;this.parent=this.busy=!1;this.initializeExtras()},createLevelDistanceFunc:function(){var a=this.config.levelDistance;return function(c){return(c._depth+1)*a}},refresh:function(){this.compute();this.plot()},reposition:function(){this.compute("end")},plot:function(){this.fx.plot()},getNodeAndParentAngle:function(a){var c=!1,b=this.graph.getNode(a),a=b.getParents();if(a=a.length>0?a[0]:!1)c=a.pos.getc(),b=b.pos.getc(),c=c.add(b.scale(-1)),c=Math.atan2(c.y,c.x),
c<0&&(c+=2*Math.PI);return{parent:a,theta:c}},tagChildren:function(a,c){if(a.angleSpan){var b=[];a.eachAdjacency(function(a){b.push(a.nodeTo)},"ignore");for(var d=b.length,e=0;e<d&&c!=b[e].id;e++);for(var e=(e+1)%d,f=0;c!=b[e].id;e=(e+1)%d)b[e].dist=f++}},onClick:function(a,c){if(this.root!=a&&!this.busy){this.busy=!0;this.root=a;that=this;this.controller.onBeforeCompute(this.graph.getNode(a));var b=this.getNodeAndParentAngle(a);this.tagChildren(b.parent,a);this.parent=b.parent;this.compute("end");
var d=b.theta-b.parent.endPos.theta;this.graph.eachNode(function(a){a.endPos.set(a.endPos.getp().add(new r(d,0)))});b=this.config.interpolation;c=g.merge({onComplete:g.empty},c||{});this.fx.animate(g.merge({hideLabels:!0,modes:[b]},c,{onComplete:function(){that.busy=!1;c.onComplete()}}))}}});$jit.RGraph.$extend=!0;(function(a){a.Op=new i({Implements:k.Op});a.Plot=new i({Implements:k.Plot});a.Label={};a.Label.Native=new i({Implements:k.Label.Native});a.Label.SVG=new i({Implements:k.Label.SVG,initialize:function(a){this.viz=
a},placeLabel:function(a,b,d){var e=b.pos.getc(!0),f=this.viz.canvas,g=f.translateOffsetX,n=f.translateOffsetY,j=f.scaleOffsetX,i=f.scaleOffsetY,f=f.getSize(),e={x:Math.round(e.x*j+g+f.width/2),y:Math.round(e.y*i+n+f.height/2)};a.setAttribute("x",e.x);a.setAttribute("y",e.y);d.onPlaceLabel(a,b)}});a.Label.HTML=new i({Implements:k.Label.HTML,initialize:function(a){this.viz=a},placeLabel:function(a,b,d){var e=b.pos.getc(!0),f=this.viz.canvas,g=f.translateOffsetX,n=f.translateOffsetY,i=f.scaleOffsetX,
k=f.scaleOffsetY,m=f.getSize(),e={x:Math.round(e.x*i+g+m.width/2),y:Math.round(e.y*k+n+m.height/2)},g=a.style;g.left=e.x+"px";g.top=e.y+"px";g.display=this.fitsInCanvas(e,f)?"":"none";d.onPlaceLabel(a,b)}});a.Plot.NodeTypes=new i({none:{render:g.empty,contains:g.lambda(!1)},circle:{render:function(a,b){var d=a.pos.getc(!0),e=a.getData("dim");this.nodeHelper.circle.render("fill",d,e,b)},contains:function(a,b){var d=a.pos.getc(!0),e=a.getData("dim");return this.nodeHelper.circle.contains(d,b,e)}},ellipse:{render:function(a,
b){var d=a.pos.getc(!0),e=a.getData("width"),f=a.getData("height");this.nodeHelper.ellipse.render("fill",d,e,f,b)},contains:function(a,b){var d=a.pos.getc(!0),e=a.getData("width"),f=a.getData("height");return this.nodeHelper.ellipse.contains(d,b,e,f)}},square:{render:function(a,b){var d=a.pos.getc(!0),e=a.getData("dim");this.nodeHelper.square.render("fill",d,e,b)},contains:function(a,b){var d=a.pos.getc(!0),e=a.getData("dim");return this.nodeHelper.square.contains(d,b,e)}},rectangle:{render:function(a,
b){var d=a.pos.getc(!0),e=a.getData("width"),f=a.getData("height");this.nodeHelper.rectangle.render("fill",d,e,f,b)},contains:function(a,b){var d=a.pos.getc(!0),e=a.getData("width"),f=a.getData("height");return this.nodeHelper.rectangle.contains(d,b,e,f)}},triangle:{render:function(a,b){var d=a.pos.getc(!0),e=a.getData("dim");this.nodeHelper.triangle.render("fill",d,e,b)},contains:function(a,b){var d=a.pos.getc(!0),e=a.getData("dim");return this.nodeHelper.triangle.contains(d,b,e)}},star:{render:function(a,
b){var d=a.pos.getc(!0),e=a.getData("dim");this.nodeHelper.star.render("fill",d,e,b)},contains:function(a,b){var d=a.pos.getc(!0),e=a.getData("dim");return this.nodeHelper.star.contains(d,b,e)}}});a.Plot.EdgeTypes=new i({none:g.empty,line:{render:function(a,b){var d=a.nodeFrom.pos.getc(!0),e=a.nodeTo.pos.getc(!0);this.edgeHelper.line.render(d,e,b)},contains:function(a,b){var d=a.nodeFrom.pos.getc(!0),e=a.nodeTo.pos.getc(!0);return this.edgeHelper.line.contains(d,e,b,this.edge.epsilon)}},arrow:{render:function(a,
b){var d=a.nodeFrom.pos.getc(!0),e=a.nodeTo.pos.getc(!0),f=a.getData("dim"),g=a.data.$direction;this.edgeHelper.arrow.render(d,e,f,g&&g.length>1&&g[0]!=a.nodeFrom.id,b)},contains:function(a,b){var d=a.nodeFrom.pos.getc(!0),e=a.nodeTo.pos.getc(!0);return this.edgeHelper.arrow.contains(d,e,b,this.edge.epsilon)}}})})($jit.RGraph);q.Tree={$extend:!0,orientation:"left",subtreeOffset:8,siblingOffset:5,indent:10,multitree:!1,align:"center"};k.Geom=new i({initialize:function(a){this.viz=a;this.config=a.config;
this.node=a.config.Node;this.edge=a.config.Edge},translate:function(a,c){c=g.splat(c);this.viz.graph.eachNode(function(b){g.each(c,function(c){b.getPos(c).$add(a)})})},setRightLevelToShow:function(a,c,b){var d=this.getRightLevelToShow(a,c),e=this.viz.labels,f=g.merge({execShow:!0,execHide:!0,onHide:g.empty,onShow:g.empty},b||{});a.eachLevel(0,this.config.levelsToShow,function(b){if(b._depth-a._depth>d){if(f.onHide(b),f.execHide)b.drawn=!1,b.exist=!1,e.hideLabel(b,!1)}else if(f.onShow(b),f.execShow)b.exist=
!0});a.drawn=!0},getRightLevelToShow:function(a,c){var b=this.config,d=b.levelsToShow;if(!b.constrained)return d;for(;!this.treeFitsInCanvas(a,c,d)&&d>1;)d--;return d}});p.TM={};p.TM.SliceAndDice=new i({compute:function(a){var c=this.graph.getNode(this.clickedNode&&this.clickedNode.id||this.root);this.controller.onBeforeCompute(c);var b=this.canvas.getSize(),d=this.config,e=b.width,b=b.height;this.graph.computeLevels(this.root,0,"ignore");c.getPos(a).setc(-e/2,-b/2);c.setData("width",e,a);c.setData("height",
b+d.titleHeight,a);this.computePositions(c,c,this.layout.orientation,a);this.controller.onAfterCompute(c)},computePositions:function(a,c,b,d){var e=0;a.eachSubnode(function(a){e+=a.getData("area",d)});var f=this.config,g=a.getData("width",d),i=a.getData("height",d)-f.titleHeight,a=a==c?1:c.getData("area",d)/e,j,k,m,l,o;b=="h"?(b="v",g*=a,j="height",k="y",m="x",l=f.titleHeight,o=0):(b="h",i*=a,j="width",k="x",m="y",l=0,o=f.titleHeight);var p=c.getPos(d);c.setData("width",g,d);c.setData("height",i,
d);var q=0,r=this;c.eachSubnode(function(a){var e=a.getPos(d);e[k]=q+p[k]+l;e[m]=p[m]+o;r.computePositions(c,a,b,d);q+=a.getData(j,d)})}});p.TM.Area={compute:function(a){var a=a||"current",c=this.graph.getNode(this.clickedNode&&this.clickedNode.id||this.root);this.controller.onBeforeCompute(c);var b=this.config,d=this.canvas.getSize(),e=d.width,d=d.height,f=b.offset,g=e-f,f=d-f;this.graph.computeLevels(this.root,0,"ignore");c.getPos(a).setc(-e/2,-d/2);c.setData("width",e,a);c.setData("height",d,a);
this.computePositions(c,{top:-d/2+b.titleHeight,left:-e/2,width:g,height:f-b.titleHeight},a);this.controller.onAfterCompute(c)},computeDim:function(a,c,b,d,e,f){if(a.length+c.length==1)this.layoutLast(a.length==1?a:c,b,d,f);else if(a.length>=2&&c.length==0&&(c=[a.shift()]),a.length==0)c.length>0&&this.layoutRow(c,b,d,f);else{var g=a[0];e(c,b)>=e([g].concat(c),b)?this.computeDim(a.slice(1),c.concat([g]),b,d,e,f):(c=this.layoutRow(c,b,d,f),this.computeDim(a,[],c.dim,c,e,f))}},worstAspectRatio:function(a,
c){if(!a||a.length==0)return Number.MAX_VALUE;for(var b=0,d=0,e=Number.MAX_VALUE,f=0,g=a.length;f<g;f++){var i=a[f]._area;b+=i;e=e<i?e:i;d=d>i?d:i}f=c*c;b*=b;return Math.max(f*d/b,b/(f*e))},avgAspectRatio:function(a,c){if(!a||a.length==0)return Number.MAX_VALUE;for(var b=0,d=0,e=a.length;d<e;d++){var f=a[d]._area/c;b+=c>f?c/f:f/c}return b/e},layoutLast:function(a,c,b,d){a=a[0];a.getPos(d).setc(b.left,b.top);a.setData("width",b.width,d);a.setData("height",b.height,d)}};p.TM.Squarified=new i({Implements:p.TM.Area,
computePositions:function(a,c,b){var d=this.config;this.layout.orientation=c.width>=c.height?"h":"v";var e=a.getSubnodes([1,1],"ignore");if(e.length>0){this.processChildrenLayout(a,e,c,b);for(var a=0,f=e.length;a<f;a++){var g=e[a],i=d.offset,c=g.getData("height",b)-i-d.titleHeight,i=g.getData("width",b)-i,j=g.getPos(b),c={width:i,height:c,top:j.y+d.titleHeight,left:j.x};this.computePositions(g,c,b)}}},processChildrenLayout:function(a,c,b,d){var a=b.width*b.height,e,f=c.length,g=0,i=[];for(e=0;e<f;e++)i[e]=
parseFloat(c[e].getData("area",d)),g+=i[e];for(e=0;e<f;e++)c[e]._area=a*i[e]/g;a=this.layout.horizontal()?b.height:b.width;c.sort(function(a,b){var c=b._area-a._area;return c?c:b.id==a.id?0:b.id<a.id?1:-1});e=[c[0]];this.squarify(c.slice(1),e,a,b,d)},squarify:function(a,c,b,d,e){this.computeDim(a,c,b,d,this.worstAspectRatio,e)},layoutRow:function(a,c,b,d){return this.layout.horizontal()?this.layoutV(a,c,b,d):this.layoutH(a,c,b,d)},layoutV:function(a,c,b,d){var e=0;g.each(a,function(a){e+=a._area});
for(var c=e/c,f=0,h=0,i=a.length;h<i;h++){var j=a[h]._area/c,k=a[h];k.getPos(d).setc(b.left,b.top+f);k.setData("width",c,d);k.setData("height",j,d);f+=j}a={height:b.height,width:b.width-c,top:b.top,left:b.left+c};a.dim=Math.min(a.width,a.height);a.dim!=a.height&&this.layout.change();return a},layoutH:function(a,c,b,d){var e=0;g.each(a,function(a){e+=a._area});for(var f=e/c,h=b.top,i=0,j=0,k=a.length;j<k;j++){var m=a[j],c=m._area/f;m.getPos(d).setc(b.left+i,h);m.setData("width",c,d);m.setData("height",
f,d);i+=c}a={height:b.height-f,width:b.width,top:b.top+f,left:b.left};a.dim=Math.min(a.width,a.height);a.dim!=a.width&&this.layout.change();return a}});p.TM.Strip=new i({Implements:p.TM.Area,computePositions:function(a,c,b){var d=a.getSubnodes([1,1],"ignore"),e=this.config;if(d.length>0){this.processChildrenLayout(a,d,c,b);for(var a=0,f=d.length;a<f;a++){var g=d[a],i=e.offset,c=g.getData("height",b)-i-e.titleHeight,i=g.getData("width",b)-i,j=g.getPos(b),c={width:i,height:c,top:j.y+e.titleHeight,left:j.x};
this.computePositions(g,c,b)}}},processChildrenLayout:function(a,c,b,d){var a=b.width*b.height,e,f=c.length,g=0,i=[];for(e=0;e<f;e++)i[e]=+c[e].getData("area",d),g+=i[e];for(e=0;e<f;e++)c[e]._area=a*i[e]/g;a=this.layout.horizontal()?b.width:b.height;e=[c[0]];this.stripify(c.slice(1),e,a,b,d)},stripify:function(a,c,b,d,e){this.computeDim(a,c,b,d,this.avgAspectRatio,e)},layoutRow:function(a,c,b,d){return this.layout.horizontal()?this.layoutH(a,c,b,d):this.layoutV(a,c,b,d)},layoutV:function(a,c,b,d){var e=
0;g.each(a,function(a){e+=a._area});for(var f=e/c,h=0,i=0,j=a.length;i<j;i++){var k=a[i],m=k._area/f;k.getPos(d).setc(b.left,b.top+(c-m-h));k.setData("width",f,d);k.setData("height",m,d);h+=m}return{height:b.height,width:b.width-f,top:b.top,left:b.left+f,dim:c}},layoutH:function(a,c,b,d){var e=0;g.each(a,function(a){e+=a._area});for(var f=e/c,h=b.height-f,i=0,j=0,k=a.length;j<k;j++){var m=a[j],l=m._area/f;m.getPos(d).setc(b.left+i,b.top+h);m.setData("width",l,d);m.setData("height",f,d);i+=l}return{height:b.height-
f,width:b.width,top:b.top,left:b.left,dim:c}}});$jit.TM={};var l=$jit.TM;$jit.TM.$extend=!0;l.Base={layout:{orientation:"h",vertical:function(){return this.orientation=="v"},horizontal:function(){return this.orientation=="h"},change:function(){this.orientation=this.vertical()?"h":"v"}},initialize:function(a){this.controller=this.config=g.merge(q("Canvas","Node","Edge","Fx","Controller","Tips","NodeStyles","Events","Navigation","Label"),{orientation:"h",titleHeight:13,offset:2,levelsToShow:0,constrained:!1,
animate:!1,Node:{type:"rectangle",overridable:!0,width:3,height:3,color:"#444"},Label:{textAlign:"center",textBaseline:"top"},Edge:{type:"none"},duration:700,fps:45},a);this.layout.orientation=this.config.orientation;a=this.config;if(a.useCanvas)this.canvas=a.useCanvas,this.config.labelContainer=this.canvas.id+"-label";else{if(a.background)a.background=g.merge({type:"Circles"},a.background);this.canvas=new u(this,a);this.config.labelContainer=(typeof a.injectInto=="string"?a.injectInto:a.injectInto.id)+
"-label"}this.graphOptions={complex:!0,Node:{selected:!1,exist:!0,drawn:!0}};this.graph=new k(this.graphOptions,this.config.Node,this.config.Edge);this.labels=new l.Label[a.Label.type](this);this.fx=new l.Plot(this);this.op=new l.Op(this);this.group=new l.Group(this);this.geom=new l.Geom(this);this.clickedNode=null;this.busy=!1;this.initializeExtras()},refresh:function(){if(!this.busy){this.busy=!0;var a=this;this.config.animate?(this.compute("end"),this.config.levelsToShow>0&&this.geom.setRightLevelToShow(this.graph.getNode(this.clickedNode&&
this.clickedNode.id||this.root)),this.fx.animate(g.merge(this.config,{modes:["linear","node-property:width:height"],onComplete:function(){a.busy=!1}}))):(this.config.Label.type!="Native"&&(a=this,this.graph.eachNode(function(c){a.labels.hideLabel(c,!1)})),this.busy=!1,this.compute(),this.config.levelsToShow>0&&this.geom.setRightLevelToShow(this.graph.getNode(this.clickedNode&&this.clickedNode.id||this.root)),this.plot())}},plot:function(){this.fx.plot()},leaf:function(a){return a.getSubnodes([1,1],
"ignore").length==0},enter:function(a){if(!this.busy){this.busy=!0;var c=this,b=this.config,d=this.graph,e=this.clickedNode,f={onComplete:function(){b.levelsToShow>0&&c.geom.setRightLevelToShow(a);(b.levelsToShow>0||b.request)&&c.compute();b.animate?(d.nodeList.setData("alpha",0,"end"),a.eachSubgraph(function(a){a.setData("alpha",1,"end")},"ignore"),c.fx.animate({duration:500,modes:["node-property:alpha"],onComplete:function(){c.clickedNode=a;c.compute("end");c.clickedNode=e;c.fx.animate({modes:["linear",
"node-property:width:height"],duration:1E3,onComplete:function(){c.busy=!1;c.clickedNode=a}})}})):(c.busy=!1,c.clickedNode=a,c.refresh())}};if(b.request)this.requestNodes(a,f);else f.onComplete()}},out:function(){if(!this.busy){this.busy=!0;this.events.hoveredNode=!1;var a=this,c=this.config,b=this.graph,d=b.getNode(this.clickedNode&&this.clickedNode.id||this.root).getParents()[0],e=this.clickedNode;if(d)if(callback={onComplete:function(){a.clickedNode=d;c.request?a.requestNodes(d,{onComplete:function(){a.compute();
a.plot();a.busy=!1}}):(a.compute(),a.plot(),a.busy=!1)}},c.levelsToShow>0&&this.geom.setRightLevelToShow(d),c.animate)this.clickedNode=d,this.compute("end"),this.clickedNode=e,this.fx.animate({modes:["linear","node-property:width:height"],duration:1E3,onComplete:function(){a.clickedNode=d;b.eachNode(function(a){a.setDataset(["current","end"],{alpha:[0,1]})},"ignore");e.eachSubgraph(function(a){a.setData("alpha",1)},"ignore");a.fx.animate({duration:500,modes:["node-property:alpha"],onComplete:function(){callback.onComplete()}})}});
else callback.onComplete();else this.busy=!1}},requestNodes:function(a,c){var b=g.merge(this.controller,c),d=this.config.levelsToShow;if(b.request){var e=[],f=a._depth;a.eachLevel(0,d,function(a){var b=d-(a._depth-f);if(a.drawn&&!a.anySubnode()&&b>0)e.push(a),a._level=b});this.group.requestNodes(e,b)}else b.onComplete()}};l.Op=new i({Implements:k.Op,initialize:function(a){this.viz=a}});l.Geom=new i({Implements:k.Geom,getRightLevelToShow:function(){return this.viz.config.levelsToShow},setRightLevelToShow:function(a){var c=
this.getRightLevelToShow(),b=this.viz.labels;a.eachLevel(0,c+1,function(d){d._depth-a._depth>c?(d.drawn=!1,d.exist=!1,d.ignore=!0,b.hideLabel(d,!1)):(d.drawn=!0,d.exist=!0,delete d.ignore)});a.drawn=!0;delete a.ignore}});l.Group=new i({initialize:function(a){this.viz=a;this.canvas=a.canvas;this.config=a.config},requestNodes:function(a,c){var b=0,d=a.length,e=this.viz;if(d==0)c.onComplete();for(var f=0;f<d;f++)c.request(a[f].id,a[f]._level,{onComplete:function(a,f){if(f&&f.children)f.id=a,e.op.sum(f,
{type:"nothing"});++b==d&&(e.graph.computeLevels(e.root,0),c.onComplete())}})}});l.Plot=new i({Implements:k.Plot,initialize:function(a){this.viz=a;this.config=a.config;this.node=this.config.Node;this.edge=this.config.Edge;this.animation=new z;this.nodeTypes=new l.Plot.NodeTypes;this.edgeTypes=new l.Plot.EdgeTypes;this.labels=a.labels},plot:function(a,c){var b=this.viz,d=b.graph;b.canvas.clear();this.plotTree(d.getNode(b.clickedNode&&b.clickedNode.id||b.root),g.merge(b.config,a||{},{withLabels:!0,
hideLabels:!1,plotSubtree:function(a){return a.anySubnode("exist")}}),c)}});l.Label={};l.Label.Native=new i({Implements:k.Label.Native,initialize:function(a){this.config=a.config;this.leaf=a.leaf},renderLabel:function(a,c){if(this.leaf(c)||this.config.titleHeight){var b=c.pos.getc(!0),d=a.getCtx(),e=c.getData("width");c.getData("height");d.fillText(c.name,b.x+e/2,b.y,e)}}});l.Label.SVG=new i({Implements:k.Label.SVG,initialize:function(a){this.viz=a;this.leaf=a.leaf;this.config=a.config},placeLabel:function(a,
c,b){var d=c.pos.getc(!0),e=this.viz.canvas,f=e.translateOffsetX,g=e.translateOffsetY,i=e.scaleOffsetX,j=e.scaleOffsetY,e=e.getSize(),d={x:Math.round(d.x*i+f+e.width/2),y:Math.round(d.y*j+g+e.height/2)};a.setAttribute("x",d.x);a.setAttribute("y",d.y);if(!this.leaf(c)&&!this.config.titleHeight)a.style.display="none";b.onPlaceLabel(a,c)}});l.Label.HTML=new i({Implements:k.Label.HTML,initialize:function(a){this.viz=a;this.leaf=a.leaf;this.config=a.config},placeLabel:function(a,c,b){var d=c.pos.getc(!0),
e=this.viz.canvas,f=e.translateOffsetX,g=e.translateOffsetY,i=e.scaleOffsetX,j=e.scaleOffsetY,e=e.getSize(),d={x:Math.round(d.x*i+f+e.width/2),y:Math.round(d.y*j+g+e.height/2)},f=a.style;f.left=d.x+"px";f.top=d.y+"px";f.width=c.getData("width")*i+"px";f.height=c.getData("height")*j+"px";f.zIndex=c._depth*100;f.display="";if(!this.leaf(c)&&!this.config.titleHeight)a.style.display="none";b.onPlaceLabel(a,c)}});l.Plot.NodeTypes=new i({none:{render:g.empty},rectangle:{render:function(a,c){var b=this.viz.leaf(a),
d=this.config,e=d.offset,f=d.titleHeight,h=a.pos.getc(!0),i=a.getData("width"),j=a.getData("height"),k=a.getData("border"),m=c.getCtx(),l=h.x+e/2,o=h.y+e/2;if(!(i<=e||j<=e))if(b){if(d.cushion)b=m.createRadialGradient(l+(i-e)/2,o+(j-e)/2,1,l+(i-e)/2,o+(j-e)/2,i<j?j:i),d=a.getData("color"),f=g.rgbToHex(g.map(g.hexToRgb(d),function(a){return a*0.2>>0})),b.addColorStop(0,d),b.addColorStop(1,f),m.fillStyle=b;m.fillRect(l,o,i-e,j-e);if(k)m.save(),m.strokeStyle=k,m.strokeRect(l,o,i-e,j-e),m.restore()}else if(f>
0&&(m.fillRect(h.x+e/2,h.y+e/2,i-e,f-e),k))m.save(),m.strokeStyle=k,m.strokeRect(h.x+e/2,h.y+e/2,i-e,j-e),m.restore()},contains:function(a,c){if(this.viz.clickedNode&&!a.isDescendantOf(this.viz.clickedNode.id)||a.ignore)return!1;var b=a.pos.getc(!0),d=a.getData("width"),e=this.viz.leaf(a)?a.getData("height"):this.config.titleHeight;return this.nodeHelper.rectangle.contains({x:b.x+d/2,y:b.y+e/2},c,d,e)}}});l.Plot.EdgeTypes=new i({none:g.empty});l.SliceAndDice=new i({Implements:[t,s,l.Base,p.TM.SliceAndDice]});
l.Squarified=new i({Implements:[t,s,l.Base,p.TM.Squarified]});l.Strip=new i({Implements:[t,s,l.Base,p.TM.Strip]})})();
