FROM consol/sakuli-ubuntu-xfce
MAINTAINER Sven Nierlein "sven@nierlein.de"
ENV REFRESHED_AT 2015-10-27

RUN apt-get update
RUN apt-get install -y apt-transport-https rsync lsof
RUN sh -c "echo 'deb https://labs.consol.de/repo/testing/ubuntu $(lsb_release -sc) main' >> /etc/apt/sources.list"
RUN gpg --keyserver keys.gnupg.net --recv-keys F8C1CA08A57B9ED7
RUN gpg --armor --export F8C1CA08A57B9ED7 | sudo apt-key add -
RUN apt-get update
RUN apt-get install -y naemon
RUN sed -e 's|#broker_module=/usr/lib/naemon/naemon-livestatus/livestatus.so|broker_module=/usr/lib/naemon/naemon-livestatus/livestatus.so|g' -i /etc/naemon/naemon.cfg
RUN sed -e 's|incognito|incognito --no-sandbox --no-default-browser-check --no-first-run --disable-infobars|g' -i /root/sakuli/sahi/config/browser_types/linux.xml
RUN rm -rf /etc/naemon/conf.d/*
RUN mkdir -p /root/cases/

COPY test.sh            /root/
COPY start_dashboard.sh /root/

WORKDIR /root
CMD ["/root/test.sh"]
