FROM consol/sakuli-ubuntu-xfce:v1.0.0
MAINTAINER Sven Nierlein "sven@nierlein.de"
ENV REFRESHED_AT 2016-06-25

RUN apt-get update
RUN apt-get install -y apt-transport-https rsync lsof patch bash-completion chromium-browser firefox
RUN sh -c "echo 'deb https://labs.consol.de/repo/testing/ubuntu $(lsb_release -sc) main' >> /etc/apt/sources.list"
RUN gpg --keyserver keys.gnupg.net --recv-keys F8C1CA08A57B9ED7
RUN gpg --armor --export F8C1CA08A57B9ED7 | sudo apt-key add -
RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
RUN apt-get update
RUN apt-get install -y naemon
RUN apt-get install -y google-chrome-stable
RUN sed -e 's|incognito|incognito --no-sandbox --no-default-browser-check --no-first-run --disable-infobars|g' -i /root/sakuli/sahi/config/browser_types/linux.xml
RUN rm -rf /etc/naemon/conf.d/*
RUN mkdir -p /root/cases/
RUN IP=$(/sbin/ifconfig | grep addr | grep -v Link | head -n 1 | awk '{ print $2}' | sed -e 's/addr://'); echo "ServerName $IP" >> /etc/apache2/sites-available/000-default.conf

COPY *.sh               /root/
COPY *.pl               /root/
COPY *.patch            /root/

RUN cd /root/ && patch -p 0 < 0001-sahi_add_color_to_highlight.js.patch

WORKDIR /root
CMD ["/root/failsafe.sh"]
