name: citest

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

env:
  THRUK_TEST_MODULES_CACHE: /tmp/thruk_test_modules_cache
  THRUK_CRITIC_CACHE_FILE:  /tmp/thruk_critic_cache_file

jobs:
  citest:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: perl -V
        run: perl -V
      - name: Setup tmate session, see https://github.com/marketplace/actions/debugging-with-tmate
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - uses: abbbi/github-actions-tune@v1
      - name: ./.ci/prepare_machine.sh
        run: timeout -v 15m sudo bash -x ./.ci/prepare_machine.sh
      - name: ./.ci/install_deps.sh
        run: timeout -v 15m sudo su naemon -c 'bash -x ./.ci/install_deps.sh'
      - name: ./script/install_puppeteer.sh
        run: timeout -v 15m sudo bash -x ./script/install_puppeteer.sh
      - name: cache files
        id: thruk-test-cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.THRUK_TEST_MODULES_CACHE }}
            ${{ env.THRUK_CRITIC_CACHE_FILE }}
          key: thruk-test-cache
      - name: make cache files writable
        run: "sudo chown -R naemon: ${{ env.THRUK_TEST_MODULES_CACHE }} ${{ env.THRUK_CRITIC_CACHE_FILE }} || :"
      - name: make citest
        run: |
          timeout -v 90m sudo su naemon -c 'eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib) && HARNESS_TIMER=1 stdbuf -o0 -e0 make citest'
